/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-13 06:44:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import trip.vo.*;
import trip.dto.*;

public final class loadReply_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("trip.vo");
    _jspx_imports_packages.add("trip.dto");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String bno = request.getParameter("no");
	userVO login  = (userVO)session.getAttribute("login");

    replyDTO rdto = new replyDTO();
    ArrayList<replyVO> rlist = rdto.GetList(bno);

    for (replyVO rvo : rlist) {

      out.write("\r\n");
      out.write("    <form>\r\n");
      out.write("        <table border=\"0\" style=\"width: 60%;\" align=\"center\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"4\"><hr style=\"width: 100%; border:0px; height:1px; background: linear-gradient(to left, transparent, #87CEEA, transparent);\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td rowspan=\"2\" style=\"text-align: center; font-size : 40px; width:150px;\">\r\n");
      out.write("                    ");

                        String icon = "😄";
                        switch (rvo.getUicon()) {
                            case "1": icon = "😄"; break;
                            case "2": icon = "😅"; break;
                            case "3": icon = "😆"; break;
                            case "4": icon = "😀"; break;
                            case "5": icon = "😨"; break;
                            case "6": icon = "👿"; break;
                            case "7": icon = "😝"; break;
                            case "8": icon = "😷"; break;
                            case "9": icon = "😴"; break;
                            case "10": icon = "😱"; break;
                        }
                    
      out.write("\r\n");
      out.write("                    ");
      out.print( icon );
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("                <td style=\"font-size: 20px;\" width=\"150\" id=\"runick\">");
      out.print( rvo.getUnick() );
      out.write("</td>\r\n");
      out.write("                <td style=\"font-size: 15px;\" id=\"rwdate\">&nbsp;&nbsp;&nbsp;");
      out.print( rvo.getRwdate() );
      out.write("</td>\r\n");
      out.write("                <td style=\"text-align: right; height: 20px; padding-right: 100px;\">\r\n");
      out.write("                    ");

                        if (login != null && (login.getUno().equals(rvo.getUno()) || login.getAdmin().equals("Y"))) {
                    
      out.write("\r\n");
      out.write("                    <div id=\"reply_div");
      out.print( rvo.getRno() );
      out.write("\">\r\n");
      out.write("                        <span class=\"reply_btn\" id=\"reply_modify\" onclick=\"reply_update(");
      out.print( rvo.getRno() );
      out.write(',');
      out.print( bno);
      out.write(");\">수정</span>\r\n");
      out.write("                        <span class=\"reply_btn\" id=\"reply_delete\" onclick=\"reply_delete(");
      out.print( rvo.getRno() );
      out.write(");\">삭제</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

                        }
                    
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"3\" style=\"padding-bottom: 30px;\" id=\"");
      out.print( rvo.getRno() );
      out.write("\"><span>");
      out.print( rvo.getRnote() );
      out.write("</span></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");

    }

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
