/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-24 06:31:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import trip.util.*;
import trip.vo.*;
import trip.dao.*;
import trip.dto.*;
import java.io.*;
import java.util.*;

public final class modify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/board/../include/head.jsp", Long.valueOf(1714715499386L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(9);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("trip.vo");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("trip.dao");
    _jspx_imports_packages.add("trip.dto");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("trip.util");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  \r\n");

// 첨부파일 저장경로
String uploadPath = "D:\\BTEAM\\trip\\src\\main\\webapp\\upload";

//로그인 여부를 세션을 통해 검사한다
userVO login  = (userVO)session.getAttribute("login");

      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"utf-8\">\r\n");
      out.write("		<title>여행추천가이드</title>\r\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/lobby.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"../css/trip.css\"/>\r\n");
      out.write("	<script src=\"../js/jquery-3.7.1.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		window.onload = function()\r\n");
      out.write("		{\r\n");
      out.write("			$(\".header1\").click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../firstmain/lobby.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\".login\")\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				if($(\"#log_info\").is(\":visible\"))\r\n");
      out.write("				{\r\n");
      out.write("					$(\"#log_info\").css(\"display\",\"none\");\r\n");
      out.write("				}else\r\n");
      out.write("				{\r\n");
      out.write("					$(\"#log_info\").toggle();\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_info\").mouseleave(function()\r\n");
      out.write("			{	\r\n");
      out.write("				$(this).toggle();\r\n");
      out.write("			})	\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_login\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/login.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_join\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/join.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_modify\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../master/user_info.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_write\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../board/write.jsp\";\r\n");
      out.write("			});		\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_admin\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../master/masterGonggiwrite.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_logout\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/logout.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#log_book\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/bookmark.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<style>\r\n");
      out.write("		.header1\r\n");
      out.write("		{\r\n");
      out.write("			cursor:pointer; cursor:hand;\r\n");
      out.write("		}	\r\n");
      out.write("	\r\n");
      out.write("		#log_info\r\n");
      out.write("		{\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			background-color: white;\r\n");
      out.write("			display: none;\r\n");
      out.write("			top: 67px;\r\n");
      out.write("			left: 1610px;\r\n");
      out.write("			z-index: 1;\r\n");
      out.write("			overflow: hidden; \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_table\r\n");
      out.write("		{	\r\n");
      out.write("			border-top: none;\r\n");
      out.write("			border-bottom: none;\r\n");
      out.write("			background-color: ghostwhite;\r\n");
      out.write("  			border-style: hidden;\r\n");
      out.write("			border-radius : 10px;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.log_td\r\n");
      out.write("		{	\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			width: 200px;\r\n");
      out.write("			height: 50px;\r\n");
      out.write("			cursor:pointer; cursor:hand;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_logout\r\n");
      out.write("		{\r\n");
      out.write("			border-bottom-left-radius : 10px;\r\n");
      out.write("			border-bottom-right-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_login\r\n");
      out.write("		{\r\n");
      out.write("			border-top-left-radius : 10px;\r\n");
      out.write("			border-top-right-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		");

			if(login == null)
			{
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ 로그인</div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_login\">로그인</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_join\">회원가입</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

			}else if(login.getAdmin().equals("Y"))
			{ 
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ \r\n");
      out.write("						\r\n");
      out.write("							");

							String icon = "😄";
							switch (login.getUicon())
							{
							case "1": icon  = "😄"; break;     				  
	                		case "2": icon  = "😆"; break;  
	                		case "3": icon  = "😅"; break;  
	                		case "4": icon  = "😀"; break;  
	                		case "5": icon  = "😨"; break;  
	                		case "6": icon  = "👿"; break;  
	                		case "7": icon  = "😝"; break;  
	                		case "8": icon  = "😷"; break;  
	                		case "9": icon  = "😴"; break;  
	                		case "10": icon  = "😱"; break;   
			                }
							
      out.write("\r\n");
      out.write("							<span style=\"font-size:30px\">");
      out.print( icon );
      out.write("</span>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						");
      out.print( login.getUname() );
      out.write(" </div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_modify\">내 정보 수정</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_book\">북마크 보기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_admin\">관리자 페이지</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_logout\">로그아웃</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

				}else
				{
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ \r\n");
      out.write("						");

						String icon = "😄";
						switch (login.getUicon())
							{
	                		case "1": icon  = "😄"; break;     				  
	                		case "2": icon  = "😆"; break;  
	                		case "3": icon  = "😅"; break;  
	                		case "4": icon  = "😀"; break;  
	                		case "5": icon  = "😨"; break;  
	                		case "6": icon  = "👿"; break;  
	                		case "7": icon  = "😝"; break;  
	                		case "8": icon  = "😷"; break;  
	                		case "9": icon  = "😴"; break;  
	                		case "10": icon  = "😱"; break;  
			                }
							
      out.write("\r\n");
      out.write("							<span style=\"font-size:30px\">");
      out.print( icon );
      out.write("</span>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.print( login.getUname() );
      out.write("</div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_modify\">내 정보 수정</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_book\">북마크 보기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_write\" onclick=\"book();\">글쓰기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_logout\">로그아웃</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

				}
			
      out.write('\r');
      out.write('\n');
      out.write("   \r\n");

request.setCharacterEncoding("UTF-8");

String pageno     = request.getParameter("page");
String type       = request.getParameter("type");
String bno        = request.getParameter("no");
String[] season   = request.getParameterValues("season"  );
String[] local    = request.getParameterValues("local"   );
String[] human    = request.getParameterValues("human"   );
String[] move     = request.getParameterValues("move"    );
String[] schedule = request.getParameterValues("schedule");
String[] uinout   = request.getParameterValues("uinout"  );
String[] keyword   = request.getParameterValues("keyword"  );
if(pageno  == null) pageno  = "1";
if(type    == null) type    = "T";
if(keyword == null) keyword = new String[] {""};
if(bno == null || bno.equals(""))
{
	response.sendRedirect("lobby.jsp");
	return;	
}

//파라메터를 생성한다.
String search_param = "";
search_param += Param.getParam(season,"season");
search_param += "&";
search_param += Param.getParam(local,"local");
search_param += "&";
search_param += Param.getParam(human,"human");
search_param += "&";
search_param += Param.getParam(move,"move");
search_param += "&";
search_param += Param.getParam(schedule,"schedule");
search_param += "&";
search_param += Param.getParam(uinout,"uinout");

String param = "";
param += "type=" + type;
param += "&";
param += "pageno=" + pageno;
param += "&";
param += "no=" + bno;
param += "&";
param += Param.getParam(keyword,"keyword");
param += "&";
param += search_param;

boardDTO bdto = new boardDTO();
boardVO  bvo  = bdto.Read(bno, false);

attachDTO adto = new attachDTO();
ArrayList<attachVO>  avos  = adto.Read(bno);


      out.write("\r\n");
      out.write("<!-- ================================================================================= -->\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){	\r\n");
      out.write("	//게시물에 기존파일이 존재하면 \r\n");
      out.write("	if(");
      out.print( avos.isEmpty() );
      out.write(" != true)\r\n");
      out.write("	{\r\n");
      out.write("		//기존 첨부파일 불러오기\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"attach.jsp\",\r\n");
      out.write("			type : \"get\",\r\n");
      out.write("			dataType : \"html\",\r\n");
      out.write("			data : \r\n");
      out.write("			{\r\n");
      out.write("				no : ");
      out.print( bno );
      out.write("\r\n");
      out.write("			},\r\n");
      out.write("			success : function(response){\r\n");
      out.write("				response = response.trim();\r\n");
      out.write("				$(\"#tblUpload\").append(response);\r\n");
      out.write("			}\r\n");
      out.write("		});				\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//첨부파일 추가 버튼 이벤트 리스너\r\n");
      out.write("	$(\"#btnAdd\").click(function(){\r\n");
      out.write("		AddAttach();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//첨부파일 추가\r\n");
      out.write("function AddAttach()\r\n");
      out.write("{\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url : \"attach.jsp\",\r\n");
      out.write("		type : \"get\",\r\n");
      out.write("		dataType : \"html\",\r\n");
      out.write("		success : function(response){\r\n");
      out.write("			response  = response.trim();\r\n");
      out.write("			//response  = response.substr(156,347);\r\n");
      out.write("			$(\"#tblUpload\").append(response);\r\n");
      out.write("		}\r\n");
      out.write("	});				\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//첨부파일 삭제 \r\n");
      out.write("function RemoveAttach(obj)\r\n");
      out.write("{\r\n");
      out.write("	var tr = $(obj).parent().parent();\r\n");
      out.write("	tr.remove();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// 수정버튼\r\n");
      out.write("function DoModify()\r\n");
      out.write("{\r\n");
      out.write("	if( $(\"#btitle\").val() == \"\" )\r\n");
      out.write("	{\r\n");
      out.write("		$(\"#btitle\").focus();\r\n");
      out.write("		alert(\"제목을 입력하세요.\");\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if( $(\"#bnote\").val() == \"\" )\r\n");
      out.write("	{\r\n");
      out.write("		$(\"#bnote\").focus();\r\n");
      out.write("		alert(\"내용을 입력하세요.\");\r\n");
      out.write("		return;\r\n");
      out.write("	}	\r\n");
      out.write("	\r\n");
      out.write("	if($(\"#season\").val() == \"\")\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"계절을 선택하세요.\");\r\n");
      out.write("		$(\"#season\").focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if($(\"#local\").val() == \"\")\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"지역을 선택하세요.\");\r\n");
      out.write("		$(\"#local\").focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(confirm(\"변경된 게시물을 작성하시겠습니까?\") == false)\r\n");
      out.write("	{\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	$(\"#modify\").submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//취소버튼\r\n");
      out.write("function DoReset()\r\n");
      out.write("{\r\n");
      out.write("	document.location = \"../board/view.jsp?");
      out.print( param );
      out.write("\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//삭제버튼\r\n");
      out.write("function DoDelete()\r\n");
      out.write("{\r\n");
      out.write("	if(confirm(\"삭제하시겠습니까\") == false)\r\n");
      out.write("	{\r\n");
      out.write("		return;			\r\n");
      out.write("	}\r\n");
      out.write("	document.location = \"../board/delete.jsp?");
      out.print( param );
      out.write("\";\r\n");
      out.write("}\r\n");
      out.write("</script>   \r\n");
      out.write("		<form id=\"modify\" name=\"modify\" method=\"post\" action=\"modifyok.jsp\" enctype=\"multipart/form-data\">\r\n");
      out.write("			<input type=\"hidden\" name=\"no\" value=\"");
      out.print( bno );
      out.write("\">\r\n");
      out.write("			<table border=\"0\" width=\"100%\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"4\" height=\"10px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"20%\"></td>\r\n");
      out.write("					<td align=\"center\" height=\"60px\" colspan=\"2\">\r\n");
      out.write("						<!-- 제목 -->\r\n");
      out.write("						<input type=\"text\" id=\"btitle\" name=\"btitle\" style=\"width:85%; height:100%; font-size:30px;\" value=\"");
      out.print( bvo.getBtitle() );
      out.write("\">\r\n");
      out.write("					</td>\r\n");
      out.write("					<td width=\"20%\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"20%\"></td>\r\n");
      out.write("					<td style=\"vertical-align:top;\" align=\"center\" colspan=\"2\">\r\n");
      out.write("					<!-- 키워드 -->\r\n");
      out.write("					✔️<select id=\"season\" name=\"season\" style=\"width:23%\">\r\n");
      out.write("							<option value=\"\">계절</option>\r\n");
      out.write("							<option value=\"봄\" ");
      out.print( bvo.getSeason().equals("봄") ? "selected" : "" );
      out.write(">봄</option>\r\n");
      out.write("							<option value=\"여름\" ");
      out.print( bvo.getSeason().equals("여름") ? "selected" : "" );
      out.write(">여름</option>\r\n");
      out.write("							<option value=\"가을\" ");
      out.print( bvo.getSeason().equals("가을") ? "selected" : "" );
      out.write(">가을</option>\r\n");
      out.write("							<option value=\"겨울\" ");
      out.print( bvo.getSeason().equals("겨울") ? "selected" : "" );
      out.write(">겨울</option>\r\n");
      out.write("						</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("					✔️<select id=\"local\" name=\"local\" style=\"width:23%\">\r\n");
      out.write("							<option value=\"\">지역</option>\r\n");
      out.write("							<option value=\"서울경기도\" ");
      out.print( bvo.getLocal().equals("서울경기도") ? "selected" : "" );
      out.write(">서울,경기도</option>\r\n");
      out.write("							<option value=\"강원도\" ");
      out.print( bvo.getLocal().equals("강원도") ? "selected" : "" );
      out.write(">강원도</option>\r\n");
      out.write("							<option value=\"충청도\" ");
      out.print( bvo.getLocal().equals("충청도") ? "selected" : "" );
      out.write(">충청도</option>\r\n");
      out.write("							<option value=\"전북\" ");
      out.print( bvo.getLocal().equals("전북") ? "selected" : "" );
      out.write(">전라북도</option>\r\n");
      out.write("							<option value=\"전남\" ");
      out.print( bvo.getLocal().equals("전남") ? "selected" : "" );
      out.write(">전라남도</option>\r\n");
      out.write("							<option value=\"경북\" ");
      out.print( bvo.getLocal().equals("경북") ? "selected" : "" );
      out.write(">경상북도</option>\r\n");
      out.write("							<option value=\"경남\" ");
      out.print( bvo.getLocal().equals("경남") ? "selected" : "" );
      out.write(">경상남도</option>\r\n");
      out.write("							<option value=\"제주\" ");
      out.print( bvo.getLocal().equals("제주") ? "selected" : "" );
      out.write(">제주도</option>\r\n");
      out.write("						</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						<select id=\"human\" name=\"human\" style=\"width:23%\">\r\n");
      out.write("							<option value=\"\">동행</option>\r\n");
      out.write("							<option value=\"가족\" ");
      out.print( bvo.getHuman().equals("가족") ? "selected" : "" );
      out.write(">가족</option>\r\n");
      out.write("							<option value=\"연인\" ");
      out.print( bvo.getHuman().equals("연인") ? "selected" : "" );
      out.write(">연인</option>\r\n");
      out.write("							<option value=\"친구\" ");
      out.print( bvo.getHuman().equals("친구") ? "selected" : "" );
      out.write(">친구</option>\r\n");
      out.write("							<option value=\"반려견\" ");
      out.print( bvo.getHuman().equals("반려견") ? "selected" : "" );
      out.write(">반려견</option>\r\n");
      out.write("						</select>	\r\n");
      out.write("						<br>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td width=\"20%\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"20%\"></td>\r\n");
      out.write("					<td style=\"vertical-align:top;\" align=\"center\" colspan=\"2\">\r\n");
      out.write("						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						<select id=\"move\" name=\"move\" style=\"width:23%\">\r\n");
      out.write("							<option value=\"\">이동</option>\r\n");
      out.write("							<option value=\"버스\" ");
      out.print( bvo.getMove().equals("버스") ? "selected" : "" );
      out.write(">버스</option>\r\n");
      out.write("							<option value=\"기차\" ");
      out.print( bvo.getMove().equals("기차") ? "selected" : "" );
      out.write(">기차</option>\r\n");
      out.write("							<option value=\"자가용\" ");
      out.print( bvo.getMove().equals("자가용") ? "selected" : "" );
      out.write(">자가용</option>\r\n");
      out.write("							<option value=\"자전거\" ");
      out.print( bvo.getMove().equals("자전거") ? "selected" : "" );
      out.write(">자전거</option>\r\n");
      out.write("						</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						<select id=\"schedule\" name=\"schedule\" style=\"width:23%\">\r\n");
      out.write("							<option value=\"\" >일정</option>\r\n");
      out.write("							<option value=\"당일\" ");
      out.print( bvo.getSchedule().equals("당일") ? "selected" : "" );
      out.write(">당일</option>\r\n");
      out.write("							<option value=\"숙박\" ");
      out.print( bvo.getSchedule().equals("숙박") ? "selected" : "" );
      out.write(">숙박</option>\r\n");
      out.write("						</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						<select id=\"uinout\" name=\"uinout\" style=\"width:23%\">\r\n");
      out.write("							<option value=\"\">장소</option>\r\n");
      out.write("							<option value=\"실내\" ");
      out.print( bvo.getUinout().equals("실내") ? "selected" : "" );
      out.write(">실내</option>\r\n");
      out.write("							<option value=\"실외\" ");
      out.print( bvo.getUinout().equals("실외") ? "selected" : "" );
      out.write(">실외</option>\r\n");
      out.write("						</select>		\r\n");
      out.write("						<br>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td width=\"20%\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"20%\"></td>\r\n");
      out.write("					<td align=\"center\" colspan=\"2\">\r\n");
      out.write("						<!-- 내용 -->\r\n");
      out.write("						<textarea id=\"bnote\" name=\"bnote\" style=\"width:85%; height:300px;\">");
      out.print( bvo.getBnote().replace("<br>","\n") );
      out.write("</textarea>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td width=\"20%\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr bgcolor=\"#d9d9d9\">\r\n");
      out.write("					<td colspan=\"4\" align=\"center\">\r\n");
      out.write("						<span>\r\n");
      out.write("					   		<input type=\"button\" id=\"btnAdd\" name=\"btnAdd\" value=\"첨부파일 추가\">\r\n");
      out.write("					   		<table id=\"tblUpload\" border=\"1\" width=\"500px\">\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>삭제</th><!-- 삭제할 첨부파일 체크박스 -->\r\n");
      out.write("									<th>첨부파일</th><!-- 첨부파일 이름뜨는곳 -->\r\n");
      out.write("									<th width=\"100px\">비고</th><!-- 첨부파일추가 칸 지우기 -->\r\n");
      out.write("								</tr>\r\n");
      out.write("							</table>\r\n");
      out.write("						</span><br>\r\n");
      out.write("						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						<input type=\"button\" class=\"wwhite\" onclick=\"DoModify();\" value=\"수정\">\r\n");
      out.write("						<input type=\"reset\" class=\"wwhite\" onclick=\"DoReset();\" value=\"취소\">\r\n");
      out.write("						<input type=\"button\" class=\"wwhite\" onclick=\"DoDelete()\" value=\"삭제\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"20%\"></td>\r\n");
      out.write("					<td colspan=\"2\" align=\"center\"></td>\r\n");
      out.write("					<td width=\"20%\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
