/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-20 08:34:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.master;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import trip.vo.*;
import trip.dao.*;
import trip.dto.*;
import java.io.*;
import java.util.*;

public final class masterMembercheckView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/master/../include/head.jsp", Long.valueOf(1718259960266L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("trip.vo");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("trip.dao");
    _jspx_imports_packages.add("trip.dto");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  \r\n");

// 첨부파일 저장경로
String uploadPath = "D:\\BTEAM\\trip\\src\\main\\webapp\\upload";

//로그인 여부를 세션을 통해 검사한다
userVO login  = (userVO)session.getAttribute("login");

      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"utf-8\">\r\n");
      out.write("		<title>여행추천가이드</title>\r\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/lobby.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"../css/trip.css\"/>\r\n");
      out.write("	<script src=\"../js/jquery-3.7.1.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		window.onload = function()\r\n");
      out.write("		{\r\n");
      out.write("			$(\".header1\").click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../firstmain/lobby.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\".login\")\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				if($(\"#log_info\").is(\":visible\"))\r\n");
      out.write("				{\r\n");
      out.write("					$(\"#log_info\").css(\"display\",\"none\");\r\n");
      out.write("				}else\r\n");
      out.write("				{\r\n");
      out.write("					$(\"#log_info\").toggle();\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_info\").mouseleave(function()\r\n");
      out.write("			{	\r\n");
      out.write("				$(this).toggle();\r\n");
      out.write("			})	\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_login\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/login.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_join\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/join.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_modify\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../master/user_info.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_write\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../board/write.jsp\";\r\n");
      out.write("			});		\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_admin\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../master/masterGonggiwrite.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_logout\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/logout.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#log_book\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/bookmark.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<style>\r\n");
      out.write("		.header1\r\n");
      out.write("		{\r\n");
      out.write("			cursor:pointer; cursor:hand;\r\n");
      out.write("		}	\r\n");
      out.write("	\r\n");
      out.write("		#log_info\r\n");
      out.write("		{\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			background-color: white;\r\n");
      out.write("			display: none;\r\n");
      out.write("			top: 67px;\r\n");
      out.write("			left: 1610px;\r\n");
      out.write("			z-index: 1;\r\n");
      out.write("			overflow: hidden;\r\n");
      out.write("			border-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_table\r\n");
      out.write("		{	\r\n");
      out.write("			border-top: none;\r\n");
      out.write("			border-bottom: none;\r\n");
      out.write("			background-color: ghostwhite;\r\n");
      out.write("  			border-style: hidden;\r\n");
      out.write("			border-radius : 10px;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.log_td\r\n");
      out.write("		{	\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			width: 200px;\r\n");
      out.write("			height: 50px;\r\n");
      out.write("			cursor:pointer; cursor:hand;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_logout\r\n");
      out.write("		{\r\n");
      out.write("			border-bottom-left-radius : 10px;\r\n");
      out.write("			border-bottom-right-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_login\r\n");
      out.write("		{\r\n");
      out.write("			border-top-left-radius : 10px;\r\n");
      out.write("			border-top-right-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		");

			if(login == null)
			{
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ 로그인</div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_login\">로그인</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_join\">회원가입</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

			}else if(login.getAdmin().equals("Y"))
			{ 
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ \r\n");
      out.write("						\r\n");
      out.write("							");

							String icon = "😄";
							switch (login.getUicon())
							{
							case "1": icon  = "😄"; break;     				  
	                		case "2": icon  = "😆"; break;  
	                		case "3": icon  = "😅"; break;  
	                		case "4": icon  = "😀"; break;  
	                		case "5": icon  = "😨"; break;  
	                		case "6": icon  = "👿"; break;  
	                		case "7": icon  = "😝"; break;  
	                		case "8": icon  = "😷"; break;  
	                		case "9": icon  = "😴"; break;  
	                		case "10": icon  = "😱"; break;   
			                }
							
      out.write("\r\n");
      out.write("							<span style=\"font-size:30px\">");
      out.print( icon );
      out.write("</span>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						");
      out.print( login.getUname() );
      out.write(" </div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_modify\">내 정보 수정</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_book\">북마크 보기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_admin\">관리자 페이지</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_logout\">로그아웃</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

				}else
				{
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ \r\n");
      out.write("						");

						String icon = "😄";
						switch (login.getUicon())
							{
	                		case "1": icon  = "😄"; break;     				  
	                		case "2": icon  = "😆"; break;  
	                		case "3": icon  = "😅"; break;  
	                		case "4": icon  = "😀"; break;  
	                		case "5": icon  = "😨"; break;  
	                		case "6": icon  = "👿"; break;  
	                		case "7": icon  = "😝"; break;  
	                		case "8": icon  = "😷"; break;  
	                		case "9": icon  = "😴"; break;  
	                		case "10": icon  = "😱"; break;  
			                }
							
      out.write("\r\n");
      out.write("							<span style=\"font-size:30px\">");
      out.print( icon );
      out.write("</span>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.print( login.getUname() );
      out.write("</div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_modify\">내 정보 수정</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_book\">북마크 보기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_write\" onclick=\"book();\">글쓰기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_logout\">로그아웃</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

				}
			
      out.write('\r');
      out.write('\n');
      out.write(" \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/masterGonggiwrite.css\">    \r\n");

//-------------------- 값 수령 --------------------
String pageno        = request.getParameter("page");
String search_type   = request.getParameter("search_type");
String detail_retire = request.getParameter("detail_retire");
String detail_ustop  = request.getParameter("detail_ustop");
String detail_admin  = request.getParameter("detail_admin");
String detail_all    = request.getParameter("detail_all");
String keyword       = request.getParameter("keyword");
String sort_type     = request.getParameter("sort_type");
String uno           = request.getParameter("uno");

//페이징 기본설정
if(pageno == null || pageno.equals("")) 
pageno  = "1"; 
if( search_type   == null )  search_type   = "";
if( detail_retire == null )  detail_retire = "N";
if( detail_ustop  == null )  detail_ustop  = "N";
if( detail_admin  == null )  detail_admin  = "N";
if( detail_all    == null )  detail_all    = "Y";
if( keyword       == null )  keyword       = "";
if( sort_type     == null )  sort_type     = "by_number";


int curpage = 1;
try{
		curpage = Integer.parseInt(pageno);
}catch(Exception e){  }

// -------------------- DTO 선언 -------------------
userDTO dto = new userDTO();
userVO vo = new userVO();
//--------------------- 접근제어 ------------------

// 비로그인시
if(login == null)
{
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		alert(\"로그인이 필요합니다.\");\r\n");
      out.write("		if(confirm(\"로그인 페이지로 이동하시겠습니까?\") == true)\r\n");
      out.write("		{\r\n");
      out.write("			document.location = \"../user/login.jsp\";\r\n");
      out.write("			return;\r\n");
      out.write("		}else\r\n");
      out.write("		{\r\n");
      out.write("			document.location = \"../firstmain/lobby.jsp\";\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("	");
 
	return;
}

// 관리자 권한이 없을시
adminboardDTO adto = new adminboardDTO();
adminboardVO avo = new adminboardVO();

if(adto.CheckAdmin(login.getUid()) == false)
{
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		alert(\"해당 회원은 관리자 권한이 없습니다.\");\r\n");
      out.write("		history.back();\r\n");
      out.write("		return;\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("	");
 
	return;
}

//회원번호 유효성 확인
if(uno == null || uno.equals(""))
{
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		alert(\"유효하지 않은 공지글입니다.\");\r\n");
      out.write("		history.back();\r\n");
      out.write("		return;\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("	");
 
	return;
}

//--------------------- 해당회원 정보조회 ------------------- 
vo = dto.CheckUser(uno);
if(vo == null || vo.equals(""))
{
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		alert(\"해당 공지글을 조회할 수 없습니다.\");\r\n");
      out.write("		history.back();\r\n");
      out.write("		return;\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("	");
 
	return;
}

//----------------- 관심분야 받기 -----------------
String season   = "";
String local    = "";
String human    = "";
String move     = "";
String schedule = "";
String uinout   = "";

//선호계절 받기
if(vo.getSeason() == null || vo.getSeason().equals(""))
{
	season = "없음";
}else
{
	season = vo.getSeason();
}

//선호지역 받기
if(vo.getLocal() == null || vo.getLocal().equals(""))
{
	local = "없음";
}else
{
	local = vo.getLocal();
}

//선호동행수 받기
if(vo.getHuman() == null || vo.getHuman().equals(""))
{
	human = "없음";
}else
{
	human = vo.getHuman();
}

//선호이동수단 받기
if(vo.getMove() == null || vo.getMove().equals(""))
{
	move = "없음";
}else
{
	move = vo.getMove();
}

//선호일정 받기
if(vo.getSchedule() == null || vo.getSchedule().equals(""))
{
	schedule = "없음";
}else
{
	schedule = vo.getSchedule();
}

//선호장소 받기
if(vo.getUinout() == null || vo.getUinout().equals(""))
{
	uinout = "없음";
}else
{
	uinout = vo.getUinout();
}

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".btn\r\n");
      out.write("{\r\n");
      out.write("	border: 0px; \r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	border-radius: 0.2em;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	color: white; \r\n");
      out.write("	margin-bottom : 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".xx\r\n");
      out.write("{\r\n");
      out.write("	border-spacing: 20px 20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	// 유저목록 버튼\r\n");
      out.write("	function gotoList(obj)\r\n");
      out.write("	{\r\n");
      out.write("		document.location = \"masterMembercheck.jsp?\" + obj;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// 유저정보 수정 버튼\r\n");
      out.write("	function modifyUser(obj)\r\n");
      out.write("	{\r\n");
      out.write("		if(confirm(\"해당 회원정보를 수정하시겠습니까?\") == true)\r\n");
      out.write("		{\r\n");
      out.write("			document.location = \"masterMemberModify.jsp?\" + obj;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//------------- 유저 정지 체크 버튼 ----------------\r\n");
      out.write("	function userStop(uno)\r\n");
      out.write("	{\r\n");
      out.write("		var stop_date = $(\"#stop_date\").val();\r\n");
      out.write("		\r\n");
      out.write("		if(confirm(\"정지하시겠습니까?\") == false)\r\n");
      out.write("		{\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//$(\"#user_info_div\").remove()\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			url : \"masterMemberViewStop.jsp\",\r\n");
      out.write("			data : \r\n");
      out.write("			{\r\n");
      out.write("				uno : uno,\r\n");
      out.write("				stop_date : stop_date\r\n");
      out.write("			},\r\n");
      out.write("			dataType : \"html\",\r\n");
      out.write("			success : function(result)\r\n");
      out.write("			{\r\n");
      out.write("				//result = result.trim();\r\n");
      out.write("				location.reload();\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//------------- 유저 정지해제 버튼 ----------------\r\n");
      out.write("	function lift_sanctions(uno)\r\n");
      out.write("	{\r\n");
      out.write("		\r\n");
      out.write("		if(confirm(\"정지를 해제하시겠습니까?\") == false)\r\n");
      out.write("		{\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			url : \"masterMemberViewRelease.jsp\",\r\n");
      out.write("			data : \r\n");
      out.write("			{\r\n");
      out.write("				uno : uno\r\n");
      out.write("			},\r\n");
      out.write("			dataType : \"html\",\r\n");
      out.write("			success : function(result)\r\n");
      out.write("			{\r\n");
      out.write("				location.reload();\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	<form method=\"post\" name=\"masterADview\" id=\"masterADview\" action=\"masterADwrite.jsp\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- 중간부분입니다 -->\r\n");
      out.write("	<div style=\"margin-top:100px\"></div>\r\n");
      out.write("	<table border=\"0\" width=\"90%\" style=\"vertical-align:top;\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td id=\"td1\" style=\"vertical-align: top; width : 300px;\">\r\n");
      out.write("				<a href=\"masterMembercheck.jsp\" id=\"href1\"><b style=\"color:#1ABC9C\">회원조회</b></a>\r\n");
      out.write("				<hr>\r\n");
      out.write("				<a href=\"masterGonggiwrite.jsp\" id=\"href2\"><b>공지사항</b></a>\r\n");
      out.write("				<hr>\r\n");
      out.write("				<a href=\"masterADindex.jsp\" ><b>광고 관리</b></a>\r\n");
      out.write("				<hr>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td style=\"background-color:gray;\"></td>\r\n");
      out.write("			<td id=\"td2\">\r\n");
      out.write("				<table border=\"0\" width=\"100%\" align=\"center\" style=\"border-collapse: collapse;\" id=\"view\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td align=\"right\" colspan=\"4\">\r\n");
      out.write("							");
 
							String link_str = "";
							link_str += "page="+ pageno;
							link_str += "&search_type="+ search_type;
							link_str += "&detail_retire="+ detail_retire;
							link_str += "&detail_ustop="+ detail_ustop;
							link_str += "&detail_admin="+ detail_admin;
							link_str += "&detail_all="+ detail_all;
							link_str += "&keyword="+ keyword;
							link_str += "&sort_type="+ sort_type;
							link_str += "&uno="+ uno;
							
      out.write("\r\n");
      out.write("							<button type=\"button\" class =\"btn\" id=\"modify_btn\" style=\"background-color : royalblue; margin-right : 20px; font-size : 15px;\" 							\r\n");
      out.write("							onclick=\"modifyUser('");
      out.print( link_str );
      out.write("')\">회원정보 수정</button>\r\n");
      out.write("							<button type=\"button\" class =\"btn\" id=\"list_btn\" style=\"background-color : green; margin-right : 100px; font-size : 15px;\" \r\n");
      out.write("							onclick=\"gotoList('");
      out.print( link_str );
      out.write("')\">목록으로</button>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("					<div id=\"user_info_div\">\r\n");
      out.write("					<table border = \"1\"  id=\"user_info_table\" style=\"font-size : 25px; width : 800px; height : 600px; text-align : center; margin-right : 400px;\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<b>아이디</b>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td style=\"width : 250px;\">\r\n");
      out.write("								");
      out.print( vo.getUid() );
      out.write("\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<b>이름</b>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td style=\"width : 250px;\">\r\n");
      out.write("								");
      out.print( vo.getUname() );
      out.write("\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<b>닉네임</b>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								");
      out.print( vo.getUnick() );
      out.write("\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<b>탈퇴여부</b>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								");

								if(vo.getUretire() == null || vo.getUretire().equals("N"))
								{
									
      out.write(' ');
      out.write('N');
      out.write(' ');

								}else if(vo.getUretire().equals(""))
								{
									
      out.write(" 잘못된 값 ");

								}
								else
								{
									
      out.write(' ');
      out.write('Y');
      out.write(' ');

								}
								
      out.write("\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<b>이메일</b>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td colspan=\"3\">\r\n");
      out.write("								");
      out.print( vo.getEmail() );
      out.write("\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<b>사용자 이모티콘</b>\r\n");
      out.write("							</td>\r\n");
      out.write("								");
 
								String icon = "";
								if(vo.getUicon() == null || vo.getUicon().equals(""))
								{
									icon = "없음";
								}else
								{
									switch (vo.getUicon())
									{
					               		case "1": icon   = "😄"; break;	
					               		case "2": icon   = "😆"; break;  
					               		case "3": icon   = "😅"; break;  
					               		case "4": icon   = "😀"; break;  
					               		case "5": icon   = "😨"; break;  
					               		case "6": icon   = "👿"; break;  
					               		case "7": icon   = "😝"; break;  
					               		case "8": icon   = "😷"; break;  
					               		case "9": icon   = "😴"; break;  
					               		case "10": icon  = "😱"; break;  
					                }
								}
								
      out.write("\r\n");
      out.write("								<td colspan=\"3\">\r\n");
      out.write("									");
      out.print( icon );
      out.write("\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									<b>관심분야</b>\r\n");
      out.write("								</td>\r\n");
      out.write("							<td colspan=\"3\">\r\n");
      out.write("								<table border=\"1\" width=\"90%\" height=\"90%\" style=\"font-size : 18px;\">\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td><b>선호계절</b></td>\r\n");
      out.write("										<td><b>선호지역</b></td>\r\n");
      out.write("										<td><b>선호동행수</b></td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>");
      out.print( season );
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print( local );
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print( human );
      out.write("</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td><b>선호이동수단</b></td>\r\n");
      out.write("										<td><b>선호일정</b></td>\r\n");
      out.write("										<td><b>선호 장소</b></td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>");
      out.print( move );
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print( schedule );
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print( uinout );
      out.write("</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</table>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<b>회원이용정지</b>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td colspan=\"3\">\r\n");
      out.write("								<input type=\"datetime-local\" id=\"stop_date\" name=\"stop_date\" style=\"width : 350px; height : 50px; font-size : 25px;\" onchange=\"setMinValue()\">\r\n");
      out.write("								&nbsp;&nbsp;\r\n");
      out.write("								<button type=\"button\" name=\"stop2_btn\" id=\"stop2_btn\" onclick=\"userStop(");
      out.print( vo.getUno() );
      out.write(");\" \r\n");
      out.write("								style=\"width : 40px; height :30px; font-size : 15px; border-color : #ED3D45; background-color : #F0565E; border-radius: 10px;\">\r\n");
      out.write("									정지\r\n");
      out.write("								</button>\r\n");
      out.write("								<button type=\"button\" name=\"lift_sanctions_btn\" id=\"lift_sanctions_btn\" onclick=\"lift_sanctions(");
      out.print( vo.getUno() );
      out.write(");\"\r\n");
      out.write("								style=\"width : 40px; height :30px; font-size : 15px; border-color : #3D87EA; background-color : #28A6E0; border-radius: 10px;\">\r\n");
      out.write("									해제\r\n");
      out.write("								</button>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<b>정지여부</b>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td id=\"user_stop_whether\">\r\n");
      out.write("								");

								if(vo.getUstop() == null || vo.getUstop().equals("N"))
								{
									
      out.write(' ');
      out.write('N');
      out.write(' ');

								}else if(vo.getUstop().equals(""))
								{
									
      out.write(' ');

								}else
								{
									
      out.write(' ');
      out.write('Y');
      out.write(' ');

								}
								
      out.write("\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<b>정지기간</b>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td id=\"user_stop_date\" style=\"font-size : 18px;\">\r\n");
      out.write("								");

								if(vo.getUstopend() == null || vo.getUstopend().equals(""))
								{
									
      out.write(" 해당사항 없음 ");

								}else
								{
									
      out.print( vo.getUstopend() );
      out.write(' ');
      out.write('까');
      out.write('지');

								}
								
      out.write("\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("					</div>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<div style=\"height : 400px;\"> </div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<script>\r\n");
      out.write("	let stop_date = document.getElementById('stop_date');\r\n");
      out.write("	let date = new Date(new Date().getTime() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, -5);\r\n");
      out.write("\r\n");
      out.write("	stop_date.value = date;\r\n");
      out.write("	stop_date.setAttribute(\"min\", date);\r\n");
      out.write("	\r\n");
      out.write("	function setMinValue()\r\n");
      out.write("	{	\r\n");
      out.write("		if(stop_date.value < date)\r\n");
      out.write("		{\r\n");
      out.write("			alert('현재 시간보다 이전의 날짜는 설정할 수 없습니다.');\r\n");
      out.write("			stop_date.value = date;\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
