/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-20 08:01:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.master;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import trip.vo.*;
import trip.dao.*;
import trip.dto.*;
import java.io.*;
import java.util.*;

public final class masterADmodify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/master/../include/head.jsp", Long.valueOf(1718259960266L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("trip.vo");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("trip.dao");
    _jspx_imports_packages.add("trip.dto");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  \r\n");

// 첨부파일 저장경로
String uploadPath = "D:\\BTEAM\\trip\\src\\main\\webapp\\upload";

//로그인 여부를 세션을 통해 검사한다
userVO login  = (userVO)session.getAttribute("login");

      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"utf-8\">\r\n");
      out.write("		<title>여행추천가이드</title>\r\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/lobby.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"../css/trip.css\"/>\r\n");
      out.write("	<script src=\"../js/jquery-3.7.1.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		window.onload = function()\r\n");
      out.write("		{\r\n");
      out.write("			$(\".header1\").click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../firstmain/lobby.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\".login\")\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				if($(\"#log_info\").is(\":visible\"))\r\n");
      out.write("				{\r\n");
      out.write("					$(\"#log_info\").css(\"display\",\"none\");\r\n");
      out.write("				}else\r\n");
      out.write("				{\r\n");
      out.write("					$(\"#log_info\").toggle();\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_info\").mouseleave(function()\r\n");
      out.write("			{	\r\n");
      out.write("				$(this).toggle();\r\n");
      out.write("			})	\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_login\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/login.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_join\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/join.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_modify\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../master/user_info.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_write\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../board/write.jsp\";\r\n");
      out.write("			});		\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_admin\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../master/masterGonggiwrite.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_logout\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/logout.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#log_book\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/bookmark.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<style>\r\n");
      out.write("		.header1\r\n");
      out.write("		{\r\n");
      out.write("			cursor:pointer; cursor:hand;\r\n");
      out.write("		}	\r\n");
      out.write("	\r\n");
      out.write("		#log_info\r\n");
      out.write("		{\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			background-color: white;\r\n");
      out.write("			display: none;\r\n");
      out.write("			top: 67px;\r\n");
      out.write("			left: 1610px;\r\n");
      out.write("			z-index: 1;\r\n");
      out.write("			overflow: hidden;\r\n");
      out.write("			border-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_table\r\n");
      out.write("		{	\r\n");
      out.write("			border-top: none;\r\n");
      out.write("			border-bottom: none;\r\n");
      out.write("			background-color: ghostwhite;\r\n");
      out.write("  			border-style: hidden;\r\n");
      out.write("			border-radius : 10px;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.log_td\r\n");
      out.write("		{	\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			width: 200px;\r\n");
      out.write("			height: 50px;\r\n");
      out.write("			cursor:pointer; cursor:hand;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_logout\r\n");
      out.write("		{\r\n");
      out.write("			border-bottom-left-radius : 10px;\r\n");
      out.write("			border-bottom-right-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_login\r\n");
      out.write("		{\r\n");
      out.write("			border-top-left-radius : 10px;\r\n");
      out.write("			border-top-right-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		");

			if(login == null)
			{
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ 로그인</div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_login\">로그인</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_join\">회원가입</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

			}else if(login.getAdmin().equals("Y"))
			{ 
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ \r\n");
      out.write("						\r\n");
      out.write("							");

							String icon = "😄";
							switch (login.getUicon())
							{
							case "1": icon  = "😄"; break;     				  
	                		case "2": icon  = "😆"; break;  
	                		case "3": icon  = "😅"; break;  
	                		case "4": icon  = "😀"; break;  
	                		case "5": icon  = "😨"; break;  
	                		case "6": icon  = "👿"; break;  
	                		case "7": icon  = "😝"; break;  
	                		case "8": icon  = "😷"; break;  
	                		case "9": icon  = "😴"; break;  
	                		case "10": icon  = "😱"; break;   
			                }
							
      out.write("\r\n");
      out.write("							<span style=\"font-size:30px\">");
      out.print( icon );
      out.write("</span>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						");
      out.print( login.getUname() );
      out.write(" </div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_modify\">내 정보 수정</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_book\">북마크 보기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_admin\">관리자 페이지</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_logout\">로그아웃</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

				}else
				{
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ \r\n");
      out.write("						");

						String icon = "😄";
						switch (login.getUicon())
							{
	                		case "1": icon  = "😄"; break;     				  
	                		case "2": icon  = "😆"; break;  
	                		case "3": icon  = "😅"; break;  
	                		case "4": icon  = "😀"; break;  
	                		case "5": icon  = "😨"; break;  
	                		case "6": icon  = "👿"; break;  
	                		case "7": icon  = "😝"; break;  
	                		case "8": icon  = "😷"; break;  
	                		case "9": icon  = "😴"; break;  
	                		case "10": icon  = "😱"; break;  
			                }
							
      out.write("\r\n");
      out.write("							<span style=\"font-size:30px\">");
      out.print( icon );
      out.write("</span>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.print( login.getUname() );
      out.write("</div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_modify\">내 정보 수정</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_book\">북마크 보기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_write\" onclick=\"book();\">글쓰기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_logout\">로그아웃</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

				}
			
      out.write('\r');
      out.write('\n');
      out.write(" \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/masterGonggiwrite.css\">    \r\n");

//-------------------- 값 수령 --------------------
String pageno      = request.getParameter("page");
String category    = request.getParameter("category");
String subclass    = request.getParameter("subclass");
String search_type = request.getParameter("search_type");
String detail_vip  = request.getParameter("detail_vip");
String start_date  = request.getParameter("start_date");
String stop_date   = request.getParameter("stop_date");
String sort_type   = request.getParameter("sort_type");
String keyword     = request.getParameter("keyword");
String advertno    = request.getParameter("advertno");

//페이징 기본설정
if( pageno      == null  )  pageno      = "1";
if( category    == null  )  category    = "";
if( subclass    == null  )  subclass    = "";
if( search_type == null  )  search_type = "category";
if( detail_vip == null   )  detail_vip  = "N";

if( start_date == null   )
{
	start_date  = "";
}else
{
	start_date = start_date.replace(" ","T");
}

if( stop_date == null    )
{
	stop_date   = "";
}else
{
	stop_date = stop_date.replace(" ","T");
}

if( sort_type   == null  )  sort_type   = "by_category";
if( keyword      == null )  keyword     = "";

if(pageno        == null || pageno.equals("")) 
{
	pageno  = "1";
}

int curpage = 1;
try{
		curpage = Integer.parseInt(pageno);
}catch(Exception e){  }
//-------------------- DTO 선언 -------------------
advertDTO dto     = new advertDTO();
advertVO vo       = new advertVO();
adkeywordDTO kdto = new adkeywordDTO();
adkeywordVO kvo   = new adkeywordVO();
//--------------------- 접근제어 ------------------

// 비로그인시
if(login == null)
{
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		alert(\"로그인이 필요합니다.\");\r\n");
      out.write("		if(confirm(\"로그인 페이지로 이동하시겠습니까?\") == true)\r\n");
      out.write("		{\r\n");
      out.write("			document.location = \"../user/login.jsp\";\r\n");
      out.write("			return;\r\n");
      out.write("		}else\r\n");
      out.write("		{\r\n");
      out.write("			document.location = \"../firstmain/lobby.jsp\";\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("	");
 
	return;
}

// 관리자 권한이 없을시
adminboardDTO adto = new adminboardDTO();
adminboardVO avo = new adminboardVO();

if(adto.CheckAdmin(login.getUid()) == false)
{
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		alert(\"해당 회원은 관리자 권한이 없습니다.\");\r\n");
      out.write("		history.back();\r\n");
      out.write("		return;\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("	");
 
	return;
}

//게시물 번호 유효성 확인
if(advertno == null || advertno.equals(""))
{
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		alert(\"유효하지 않은 광고물입니다.\");\r\n");
      out.write("		history.back();\r\n");
      out.write("		return;\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("	");
 
	return;
}



//--------------------- 공지게시글 목록 조회 ------------------- 
vo = dto.Read(advertno);
if(vo == null || vo.equals(""))
{
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		alert(\"수정할 광고글이 존재하지 않습니다.\");\r\n");
      out.write("		history.back();\r\n");
      out.write("		return;\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("	");
 
	return;
}


      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".btn\r\n");
      out.write("{\r\n");
      out.write("	border: 0px; \r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	border-radius: 0.2em;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	color: white; \r\n");
      out.write("	margin-bottom : 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".xx\r\n");
      out.write("{\r\n");
      out.write("	border-spacing: 20px 20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	\r\n");
      out.write("	// 기존의 카테고리로 설정 \r\n");
      out.write("	$(\"#top_category\").val(\"");
      out.print( vo.getCategory() );
      out.write("\")\r\n");
      out.write("	selectChange()\r\n");
      out.write("	$(\"#sub_category\").val(\"");
      out.print( vo.getSubclass() );
      out.write("\")\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("//------------------- 공지글 수정 버튼 ----------------------\r\n");
      out.write("function DoModify()\r\n");
      out.write("{\r\n");
      out.write("	 \r\n");
      out.write("	 if($(\"#adtitle\").val() == \"\")\r\n");
      out.write("	 {\r\n");
      out.write("		 alert(\"제목을 입력하세요\");\r\n");
      out.write("		 $(\"#adtitle\").focus();\r\n");
      out.write("		 return;\r\n");
      out.write("	 }\r\n");
      out.write("	 if($(\"#fname\").val() == \"\")\r\n");
      out.write("	 {\r\n");
      out.write("		 alert(\"파일을 업로드 해주세요\");\r\n");
      out.write("		 return;\r\n");
      out.write("	 }\r\n");
      out.write("	 if($(\"#startday\").val() == \"\")\r\n");
      out.write("	 {\r\n");
      out.write("		 alert(\"시작일을 입력해주세요\");\r\n");
      out.write("		 return;\r\n");
      out.write("	 }\r\n");
      out.write("	 if($(\"#endday\").val() == \"\")\r\n");
      out.write("	 {\r\n");
      out.write("		 alert(\"종료일을 입력해주세요\");\r\n");
      out.write("		 return;\r\n");
      out.write("	 }\r\n");
      out.write("	if( confirm(\"게시물을 수정하시겠습니까?\")==true)\r\n");
      out.write("	 {\r\n");
      out.write("		$(\"#mastermodify\").submit();\r\n");
      out.write("	 }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function selectChange()\r\n");
      out.write("{ \r\n");
      out.write("	var fashion = [ \"여성패션\", \"남성패션\", \"남녀공용패션\", \"유아동패션\" ];\r\n");
      out.write("\r\n");
      out.write("	var beauty = [\r\n");
      out.write("		\"럭셔리\",\"스킨케어\",\"클린/비건뷰티\",\"클렌징/필링\", \"더마코스메틱\", \"메이크업\", \"향수\", \"남성화장품\", \r\n");
      out.write("		\"네일\", \"뷰티소품\", \"어린이화장품\", \"로드샵\", \"헤어\", \"바디\", \"선물세트/키트\"\r\n");
      out.write("		]; \r\n");
      out.write("		\r\n");
      out.write("	var child = [\r\n");
      out.write("		\"유아동패션\", \"기저귀\", \"물티슈\", \"분유/어린이식품\", \"어린이 건강식품\", \"수유용품\", \"이유용품/유아식기\", \"매트/안전용품\",\r\n");
      out.write("		\"유모차/웨건\", \"카시트\", \"아기띠/외출용품\", \"욕실용품/스킨케어\", \"위생/건강/세제\", \"유아동침구\", \"유아가구/인테리어\", \"완구/교구\", \r\n");
      out.write("		\"출산준비물/선물\", \"임부/태교용품\" \r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var food = [\r\n");
      out.write("		\"유기농/친환경 전문관\", \"과일\", \"견과/건과\", \"채소\", \"쌀/잡곡\", \"축산/계란\", \"수산물/건어물\", \"생수/음료\",\r\n");
      out.write("		\"커피/원두/차\", \"과자/초콜릿/시리얼\", \"면/통조림/가공식품\", \"가루/조미료/오일\", \"장/소스/드레싱/식초\", \"유제품/아이스크림\", \"냉장/냉동/간편요리\", \"건강식품\", \r\n");
      out.write("		\"선물세트관\", \"반찬/간편식/대용식\", \"곤약/방탄커피 외\"\r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var kitchen_utensils = [\r\n");
      out.write("		\"주방가전\", \"냄비/프라이팬\", \"주방조리도구\", \"그릇/홈세트\", \"수저/커트러리\", \"컵/텀블러/와인용품\", \"주전자/커피/티용품\", \"주방수납/정리\",\r\n");
      out.write("		\"밀폐저장/도시락\", \"주방잡화\", \"일회용품/종이컵\", \"보온/보냉용품\", \"1인가구 주방용품\", \r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var household_goods = [\r\n");
      out.write("		\"헤어\", \"바디/세안\", \"구강/면도\", \"화장지/물티슈\", \"생리대/성인기저귀\", \"기저귀\", \"세탁세제\",\r\n");
      out.write("		\"청소/주방세제\", \"탈취/방향/살충\", \"건강/의료용품\", \"세탁/청소용품\", \"욕실용품\", \"생활전기용품\", \"수납/정리\", \"주방수남/잡화\"\r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var home_interior = [\r\n");
      out.write("		\"여름 침구샵\", \"싱글하우스\", \"홈데코\", \"가구\", \"수납/정리\", \"침구\", \"커튼/블라인드\", \"카페트/쿠션/거실화\",\r\n");
      out.write("		\"수예/수선\", \"욕실용품\", \"조명/스탠드\", \"셀프인테리어\", \"원예/가드닝\", \"생활전기용품\", \"공구/철물/DIY\", \"안전/신호용품\", \r\n");
      out.write("		\"세탁/청소용품\"\r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var home_appliances = [\r\n");
      out.write("		\"TV/영상가전\", \"냉장고\", \"세탁기/건조기\", \"생활가전\", \"청소기\", \"계절가전\", \"뷰티/헤어가전\", \"건강가전\",\r\n");
      out.write("		\"주방가전\", \"노트북\", \"데스크탑\", \"모니터\", \"휴대폰\", \"태블릿PC\", \"스마트워치/밴드\", \"게임\", \r\n");
      out.write("		\"키보드/마우스\", \"저장장치\", \"프린터/복합기\", \"PC부품\",\r\n");
      out.write("		\"PC주변기기\", \"음향기기\", \"카메라\", \"전동킥보드/자전거\", \"차량용 디지털\", \"1인방송 전문관\", \"휴대폰/액세서리\"\r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var sports = [\r\n");
      out.write("		\"캠핑전문관\", \"홈트레이닝\", \"수영/수상스포츠\", \"골프\", \"자전거\", \"킥보드/스케이트\", \"낚시\", \"유아동등산/아웃도어패션\",\r\n");
      out.write("		\"스포츠신발\", \"남성스포츠의류\", \"여성스포츠의류\", \"유아스포츠의류\", \"스포츠잡화\", \"구기스포츠\", \"라켓스포츠\", \"헬스/요가/댄스\", \r\n");
      out.write("		\"복싱/검도/태권도\", \"기타스포츠\", \"스키/겨울스포츠\"\r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var car_supplies = [\r\n");
      out.write("		\"봄철 차량관리\", \"인테리어\", \"익스테리어\", \"세차/카케어\", \"차량용 전자기기\", \"차량관리/소모품\", \"RV/아웃도어\", \"부품/안전/공구\",\r\n");
      out.write("		\"오토바이용품\"\r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var book_record_DVD = [\r\n");
      out.write("		\"유아/어린이\", \"소설/에세이/시\", \"초중고참고서\", \"가정 살림\", \"건강 취미\", \"경제 경영\", \"과학/공학\", \"국어/외국어/사전\",\r\n");
      out.write("		\"대학교재\", \"만화/라이트노벨\", \"사회/정치\", \"수험서/자격증\", \"여행\", \"역사\", \"스마트워치/예술\", \"인문\", \r\n");
      out.write("		\"자기계발\", \"잡지\", \"종교\", \"청소년\", \"해외도서\", \"IT컴퓨터\", \"CD/LP\", \"DVD/블루레이\"\r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var toy_hobby = [\r\n");
      out.write("		\"신생아/영아완구\", \"로봇/작동완구\", \"역할놀이\", \"블록놀이\", \"인형\", \"물놀이/계절완구\", \"승용완구\", \"스포츠/야외완구\",\r\n");
      out.write("		\"실내대형완구\", \"STEAM완구\", \"학습완구/교구\", \"보드게임\", \"RC완구/부품\", \"퍼즐/큐브/피젯토이\", \"프라모델\", \"피규어/다이캐스트\", \r\n");
      out.write("		\"콘솔/휴대용게임기\", \"파티/미술용품\", \"DIY\", \"악기/음향기기\", \"원예/가드닝\", \"수집품\", \"연령별완구\", \"키덜트샵\"\r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var office_supplies = [\r\n");
      out.write("		\"사무용품 전문관\", \"미술/화방용품\", \"캐릭터 문구\", \"학용품/수업준비\", \"필기류\", \"노트/메모지\", \"다이어리/플래너\", \"바인더/파일\",\r\n");
      out.write("		\"파티/이벤트\", \"데코/포장용품\", \"카드/엽서/봉투\", \"앨범\", \"복사용품/라벨지\", \"보드/칠판/광고\" \r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var pet_supplies = [\r\n");
      out.write("		\"강아지 사료\", \"강아지 간식\", \"강아지 영양제\", \"강아지 용품\", \"고양이 사료\", \"고양이 간식\", \"고양이 영양제\", \"고양이 용품\",\r\n");
      out.write("		\"펫티켓 산책용품\", \"관상어 용품\", \"소동물/가축용품\" \r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var health_food = [\r\n");
      out.write("		\"건강기능식품\", \"성인용 건강식품\", \"여성용 건강식품\", \"남성용 건강식품\", \"임산부 건강식품\", \"시니어 건강식품\", \"어린이 선강식품\", \"비타민/미네랄\",\r\n");
      out.write("		\"영양제\", \"허브/식물추출물\", \"홍삼/인삼\", \"건강즙/음료\", \"꿀/프로폴리스\", \"건강분말/건강환\", \"헬스보충식품\", \"다이어트/이너뷰티\", \r\n");
      out.write("		\"헬스/요가용품\", \"건강도서\", \"건강/의료용품\", \"샐러드/닭가슴살\"\r\n");
      out.write("		];\r\n");
      out.write("	\r\n");
      out.write("	var change_sub;\r\n");
      out.write("	if( $(\"#top_category\").val() == \"패션\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub = fashion;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"뷰티\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub = beauty;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"출산/유아동\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  child;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"식품\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  food;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"주방용품\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  kitchen_utensils;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"생활용품\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  household_goods;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"홈인테리어\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  home_interior;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"가전디지털\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  home_appliances;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"스포츠/레저\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  sports;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"자동차용품\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  car_supplies;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"도서/음반/DVD\")\r\n");
      out.write("	{	\r\n");
      out.write("		change_sub =  book_record_DVD;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"완구/취미\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  toy_hobby;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"문구/오피스\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  office_supplies;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"반려동물용품\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  pet_supplies;\r\n");
      out.write("		\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"헬스/건강식품\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  health_food;\r\n");
      out.write("	}else if( $(\"#top_category\").val() == \"\")\r\n");
      out.write("	{  \r\n");
      out.write("		change_sub =  [\"선택해주세요\"];\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	$('#sub_category').empty();\r\n");
      out.write("	\r\n");
      out.write("	for(var count = 0; count < change_sub.length; count++)\r\n");
      out.write("	{\r\n");
      out.write("		var option = $(\"<option>\" + change_sub[count] + \"</option>\");\r\n");
      out.write("		$('#sub_category').append(option);            \r\n");
      out.write("	} \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//---------------- 글목록 버튼 -------------------\r\n");
      out.write("function goooList(obj)\r\n");
      out.write("{\r\n");
      out.write("	document.location = \"masterADindex.jsp?\" + obj;\r\n");
      out.write("}\r\n");
      out.write("//---------------- 광고 수정완료 버튼 -------------------\r\n");
      out.write("function DoModify()\r\n");
      out.write("{\r\n");
      out.write("	\r\n");
      out.write("	if( confirm(\"광고물 수정을 완료하시겠습니까?\") == true)\r\n");
      out.write("	{\r\n");
      out.write("		$(\"#masterADmodify\").submit();\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//---------------- 수정최소 버튼 -------------------\r\n");
      out.write("function CancelModify(obj)\r\n");
      out.write("{\r\n");
      out.write("	if( confirm(\"수정을 취소하시겠습니까?\") == true)\r\n");
      out.write("	{\r\n");
      out.write("		history.back();\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	<form method=\"post\" name=\"masterADmodify\" id=\"masterADmodify\" action=\"masterADmodifyOK.jsp\">\r\n");
      out.write("	<input type=\"hidden\" id=\"for_link_page\" name=\"page\" value=\"");
      out.print( pageno );
      out.write("\">\r\n");
      out.write("	<input type=\"hidden\" id=\"for_link_category\" name=\"category\" value=\"");
      out.print( category );
      out.write("\">\r\n");
      out.write("	<input type=\"hidden\" id=\"for_link_subclass\" name=\"subclass\" value=\"");
      out.print( subclass );
      out.write("\">\r\n");
      out.write("	<input type=\"hidden\" id=\"for_link_search_type\" name=\"search_type\" value=\"");
      out.print( search_type );
      out.write("\">\r\n");
      out.write("	<input type=\"hidden\" id=\"for_link_detail_vip\" name=\"detail_vip\" value=\"");
      out.print( detail_vip );
      out.write("\">\r\n");
      out.write("	<input type=\"hidden\" id=\"for_link_sort_type\" name=\"sort_type\" value=\"");
      out.print( sort_type );
      out.write("\">\r\n");
      out.write("	<input type=\"hidden\" id=\"for_link_keyword\" name=\"keyword\" value=\"");
      out.print( keyword );
      out.write("\">\r\n");
      out.write("	<input type=\"hidden\" id=\"advertno\" name=\"advertno\" value=\"");
      out.print( advertno );
      out.write("\">\r\n");
      out.write("	<!-- 중간부분입니다 -->\r\n");
      out.write("	<div style=\"margin-top:100px\"></div>\r\n");
      out.write("	<div style=\"margin-top:100px\"></div>\r\n");
      out.write("	<table border=\"0\" width=\"90%\" style=\"vertical-align:top;\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td id=\"td1\" style=\"vertical-align:top; width : 300px;\">\r\n");
      out.write("				<a href=\"masterMembercheck.jsp\" ><b>회원조회</b></a>\r\n");
      out.write("				<hr>\r\n");
      out.write("				<a href=\"masterGonggiwrite.jsp\" ><b>공지사항</b></a>\r\n");
      out.write("				<hr>\r\n");
      out.write("				<a href=\"masterADindex.jsp\" ><b style=\"color:#1ABC9C\">광고 관리</b></a>\r\n");
      out.write("				<hr>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td style=\"background-color:gray;\"></td>\r\n");
      out.write("			<td id=\"td2\">\r\n");
      out.write("					<table border=\"0\" width=\"90%\" align=\"center\" style=\"border-collapse: collapse;\" id=\"view\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"5\" align=\"right\">\r\n");
      out.write("								");
 
								String link_str = "";
								link_str += "page="+ pageno;
								link_str += "&category="+ category;
								link_str += "&subclass="+ subclass;
								link_str += "&search_type="+ search_type;
								link_str += "&detail_vip="+ detail_vip;
								link_str += "&keyword="+ keyword;
								link_str += "&sort_type="+ sort_type;
								link_str += "&advertno="+ vo.getAdvertno();
								
      out.write("\r\n");
      out.write("								<button type=\"button\" class =\"btn\" id=\"list_btn\" style=\"background-color : #008000;  font-size : 15px; margin-right : 60px;\" \r\n");
      out.write("								onclick=\"gotoList('");
      out.print( link_str );
      out.write("')\">글목록으로</button>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("												<table border=\"1\" width=\"70%\" style=\"text-align : center; text\">\r\n");
      out.write("													<tr class=\"xx\">\r\n");
      out.write("														<th width=\"120px\">상위 카테고리</th>\r\n");
      out.write("														<td width=\"150px\">\r\n");
      out.write("														<select id=\"top_category\" onchange=\"selectChange()\" name=\"top_category\" style=\"width : 150px; text-align : center; font-size : 15px;\">\r\n");
      out.write("															<option value=\"\">선택해주세요</option>\r\n");
      out.write("															");

																advertDTO adto_for_cate = new advertDTO();
																advertVO avo_for_cate = new advertVO();
																List<advertVO> top_list = adto_for_cate.GetCategory();
																for(advertVO advo : top_list)
																{
																	
      out.write("<option value=\"");
      out.print( advo.getCategory() );
      out.write('"');
      out.write('>');
      out.print( advo.getCategory() );
      out.write("</option>");
 
																}
															
      out.write("\r\n");
      out.write("														</select>\r\n");
      out.write("														</td>\r\n");
      out.write("														<th width=\"120px\">하위 카테고리</th> \r\n");
      out.write("														<td width=\"150px\">\r\n");
      out.write("															<select id=\"sub_category\" name=\"sub_category\" style=\"width : 150px; text-align : center; font-size : 15px;\">\r\n");
      out.write("																<option value=\"\">선택해주세요</option>\r\n");
      out.write("															</select>\r\n");
      out.write("														</td>\r\n");
      out.write("													</tr>\r\n");
      out.write("													<tr>\r\n");
      out.write("														<th>상품 번호</th> \r\n");
      out.write("														<td>");
      out.print( vo.getAdvertno() );
      out.write("</td>\r\n");
      out.write("														<th>상품 VIP여부</th>\r\n");
      out.write("														<td>\r\n");
      out.write("															<label>Y</label>\r\n");
      out.write("															<input type=\"radio\" name=\"vip_whether\" id=\"vip_whether_Y\" value=\"Y\" ");
      out.print( vo.getVipWhether().equals("1") ? "checked" : "" );
      out.write(">\r\n");
      out.write("															<label style=\"margin-left : 40px;\">N</label>\r\n");
      out.write("															<input type=\"radio\" name=\"vip_whether\" id=\"vip_whether_N\" value=\"N\" ");
      out.print( vo.getVipWhether().equals("0") ? "checked" : "" );
      out.write(">\r\n");
      out.write("														</td>\r\n");
      out.write("													</tr>\r\n");
      out.write("													<tr class=\"xx\">\r\n");
      out.write("														<th>상품명</th>\r\n");
      out.write("														<td colspan=\"3\">\r\n");
      out.write("															<input type=\"text\" id=\"product_name\" name=\"product_name\" value=\"");
      out.print( vo.getProductName() );
      out.write("\" style=\"width : 90%;\">\r\n");
      out.write("														</td>\r\n");
      out.write("													</tr>\r\n");
      out.write("													<tr>\r\n");
      out.write("														<th>상품 가격</th> \r\n");
      out.write("														<td>\r\n");
      out.write("														<input type=\"text\" id=\"product_price\" name=\"product_price\" value=\"");
      out.print( vo.getPrice() );
      out.write("\" style=\"width : 150px;\">원\r\n");
      out.write("														</td>\r\n");
      out.write("														<th>VIP 선정 횟수</th> \r\n");
      out.write("														<td>");
      out.print( vo.getVipTimes() );
      out.write("</td>\r\n");
      out.write("													</tr>\r\n");
      out.write("													<tr>\r\n");
      out.write("														<th>VIP 시작일</th>\r\n");
      out.write("														<td colspan=\"1\">\r\n");
      out.write("															<input type=\"datetime-local\" class=\"date_setting\" id=\"start_date\" name=\"start_date\" \r\n");
      out.write("															style=\"width : 200px; height : 30px; font-size : 15px;\" onchange=\"setStartMinValue()\">\r\n");
      out.write("															<span class=\"block_date_setting\" style=\"display : none\">해당사항 없음</span>\r\n");
      out.write("														</td>\r\n");
      out.write("														<th>VIP 종료일</th>\r\n");
      out.write("														<td colspan=\"1\">\r\n");
      out.write("															<input type=\"datetime-local\" class=\"date_setting\" id=\"stop_date\" name=\"stop_date\" \r\n");
      out.write("															style=\"width : 200px; height : 30px; font-size : 15px;\" onchange=\"setStopMinValue()\">\r\n");
      out.write("															<span class=\"block_date_setting\" style=\"display : none\">해당사항 없음</span>\r\n");
      out.write("														</td>\r\n");
      out.write("													</tr>\r\n");
      out.write("													<tr class=\"xx\">\r\n");
      out.write("														<th>광고 이미지</th>\r\n");
      out.write("														<td colspan=\"3\"><img src=\"");
      out.print( vo.getImageURL() );
      out.write("\"></td>\r\n");
      out.write("													</tr>\r\n");
      out.write("													<tr>\r\n");
      out.write("														<th>상품 상세 URL</th>\r\n");
      out.write("														<td colspan=\"3\" style=\"font-size : 15px; text-align : left;\"><input type=\"text\" name=\"detail_URL\" id=\"detail_URL\" style=\"width : 100%;\"value=\"");
      out.print( vo.getDetailURL() );
      out.write("\"></td>\r\n");
      out.write("													</tr>\r\n");
      out.write("												</table>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"5\" align=\"right\">\r\n");
      out.write("					<button type=\"reset\" class =\"btn\" id=\"reset_btn\" \r\n");
      out.write("					style=\"color : #EF5F8E; font-size : 15px; margin-right : 20px; border-color: red; background-color : white;\">초기화</button>\r\n");
      out.write("					<button type=\"button\" class =\"btn\" id=\"cancel_btn\" style=\"background-color : #EF5F8E;  font-size : 15px; margin-right : 60px;\" \r\n");
      out.write("					onclick=\"CancelModify('");
      out.print( link_str );
      out.write("')\">수정 취소</button>\r\n");
      out.write("					<button type=\"button\" class =\"btn\" id=\"modify_btn\" style=\"background-color : #7CADFF; font-size : 15px; margin-right : 120px;\"\r\n");
      out.write("					onclick=\"DoModify()\">수정 완료</button>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<div style=\"height : 600px;\"></div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		if($('input[id=vip_whether_N]').is(\":checked\") == true)\r\n");
      out.write("		{\r\n");
      out.write("			$(\".date_setting\").css(\"display\",\"none\");\r\n");
      out.write("			$(\".block_date_setting\").css(\"display\",\"\");\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$('input[name=vip_whether]').change(function(){\r\n");
      out.write("			if($(this).val() == 'Y')\r\n");
      out.write("			{\r\n");
      out.write("				$(\".date_setting\").css(\"display\",\"\");\r\n");
      out.write("				$(\".block_date_setting\").css(\"display\",\"none\");\r\n");
      out.write("				\r\n");
      out.write("			}else if($(this).val() == 'N')\r\n");
      out.write("			{\r\n");
      out.write("				$(\".date_setting\").css(\"display\",\"none\");\r\n");
      out.write("				$(\".block_date_setting\").css(\"display\",\"\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("			\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	let date = new Date(new Date().getTime() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, -5);\r\n");
      out.write("	let start_date = document.getElementById('start_date');\r\n");
      out.write("	");
 if(!start_date.equals(""))
		{
			
      out.write("\r\n");
      out.write("			start_date.value =\"");
      out.print( start_date );
      out.write("\"\r\n");
      out.write("			console.log(\"");
      out.print( start_date );
      out.write("\")\r\n");
      out.write("			");

		}else
		{
			
      out.write("\r\n");
      out.write("			start_date.value = date;\r\n");
      out.write("			");

		}
		
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	start_date.setAttribute(\"min\", date);\r\n");
      out.write("	\r\n");
      out.write("	let stop_date  = document.getElementById('stop_date');\r\n");
      out.write("	");
 if(!stop_date.equals(""))
	{
		
      out.write("\r\n");
      out.write("		stop_date.value =\"");
      out.print( stop_date );
      out.write("\"\r\n");
      out.write("		console.log(\"");
      out.print( stop_date );
      out.write("\")\r\n");
      out.write("		");

	}else
	{
		
      out.write("\r\n");
      out.write("		stop_date.value = date;\r\n");
      out.write("		");

	}
	
      out.write("\r\n");
      out.write("	stop_date.setAttribute(\"min\", date);\r\n");
      out.write("	\r\n");
      out.write("	function setStartMinValue()\r\n");
      out.write("	{	\r\n");
      out.write("		if(start_date.value < date)\r\n");
      out.write("		{\r\n");
      out.write("			alert('현재 시간보다 이전의 날짜는 설정할 수 없습니다.');\r\n");
      out.write("			start_date.value = date;\r\n");
      out.write("	    }\r\n");
      out.write("		\r\n");
      out.write("		stop_date.value = start_date.value;\r\n");
      out.write("		stop_date.setAttribute(\"min\", start_date.value);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function setStopMinValue()\r\n");
      out.write("	{	\r\n");
      out.write("		if(stop_date.value < start_date.value)\r\n");
      out.write("		{\r\n");
      out.write("			alert('시작일보다 이전의 날짜는 설정할 수 없습니다.');\r\n");
      out.write("			start_date.value = date;\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
