/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-18 01:28:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.master;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import trip.vo.*;
import trip.dao.*;
import trip.dto.*;
import java.io.*;
import java.util.*;

public final class user_005finfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/master/../include/head.jsp", Long.valueOf(1718259960266L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("trip.vo");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("trip.dao");
    _jspx_imports_packages.add("trip.dto");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  \r\n");

// 첨부파일 저장경로
String uploadPath = "D:\\BTEAM\\trip\\src\\main\\webapp\\upload";

//로그인 여부를 세션을 통해 검사한다
userVO login  = (userVO)session.getAttribute("login");

      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"utf-8\">\r\n");
      out.write("		<title>여행추천가이드</title>\r\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/lobby.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"../css/trip.css\"/>\r\n");
      out.write("	<script src=\"../js/jquery-3.7.1.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		window.onload = function()\r\n");
      out.write("		{\r\n");
      out.write("			$(\".header1\").click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../firstmain/lobby.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\".login\")\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				if($(\"#log_info\").is(\":visible\"))\r\n");
      out.write("				{\r\n");
      out.write("					$(\"#log_info\").css(\"display\",\"none\");\r\n");
      out.write("				}else\r\n");
      out.write("				{\r\n");
      out.write("					$(\"#log_info\").toggle();\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_info\").mouseleave(function()\r\n");
      out.write("			{	\r\n");
      out.write("				$(this).toggle();\r\n");
      out.write("			})	\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_login\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/login.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_join\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/join.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_modify\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../master/user_info.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_write\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../board/write.jsp\";\r\n");
      out.write("			});		\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_admin\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../master/masterGonggiwrite.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_logout\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/logout.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#log_book\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/bookmark.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<style>\r\n");
      out.write("		.header1\r\n");
      out.write("		{\r\n");
      out.write("			cursor:pointer; cursor:hand;\r\n");
      out.write("		}	\r\n");
      out.write("	\r\n");
      out.write("		#log_info\r\n");
      out.write("		{\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			background-color: white;\r\n");
      out.write("			display: none;\r\n");
      out.write("			top: 67px;\r\n");
      out.write("			left: 1610px;\r\n");
      out.write("			z-index: 1;\r\n");
      out.write("			overflow: hidden;\r\n");
      out.write("			border-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_table\r\n");
      out.write("		{	\r\n");
      out.write("			border-top: none;\r\n");
      out.write("			border-bottom: none;\r\n");
      out.write("			background-color: ghostwhite;\r\n");
      out.write("  			border-style: hidden;\r\n");
      out.write("			border-radius : 10px;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.log_td\r\n");
      out.write("		{	\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			width: 200px;\r\n");
      out.write("			height: 50px;\r\n");
      out.write("			cursor:pointer; cursor:hand;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_logout\r\n");
      out.write("		{\r\n");
      out.write("			border-bottom-left-radius : 10px;\r\n");
      out.write("			border-bottom-right-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_login\r\n");
      out.write("		{\r\n");
      out.write("			border-top-left-radius : 10px;\r\n");
      out.write("			border-top-right-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		");

			if(login == null)
			{
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ 로그인</div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_login\">로그인</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_join\">회원가입</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

			}else if(login.getAdmin().equals("Y"))
			{ 
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ \r\n");
      out.write("						\r\n");
      out.write("							");

							String icon = "😄";
							switch (login.getUicon())
							{
							case "1": icon  = "😄"; break;     				  
	                		case "2": icon  = "😆"; break;  
	                		case "3": icon  = "😅"; break;  
	                		case "4": icon  = "😀"; break;  
	                		case "5": icon  = "😨"; break;  
	                		case "6": icon  = "👿"; break;  
	                		case "7": icon  = "😝"; break;  
	                		case "8": icon  = "😷"; break;  
	                		case "9": icon  = "😴"; break;  
	                		case "10": icon  = "😱"; break;   
			                }
							
      out.write("\r\n");
      out.write("							<span style=\"font-size:30px\">");
      out.print( icon );
      out.write("</span>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						");
      out.print( login.getUname() );
      out.write(" </div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_modify\">내 정보 수정</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_book\">북마크 보기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_admin\">관리자 페이지</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_logout\">로그아웃</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

				}else
				{
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ \r\n");
      out.write("						");

						String icon = "😄";
						switch (login.getUicon())
							{
	                		case "1": icon  = "😄"; break;     				  
	                		case "2": icon  = "😆"; break;  
	                		case "3": icon  = "😅"; break;  
	                		case "4": icon  = "😀"; break;  
	                		case "5": icon  = "😨"; break;  
	                		case "6": icon  = "👿"; break;  
	                		case "7": icon  = "😝"; break;  
	                		case "8": icon  = "😷"; break;  
	                		case "9": icon  = "😴"; break;  
	                		case "10": icon  = "😱"; break;  
			                }
							
      out.write("\r\n");
      out.write("							<span style=\"font-size:30px\">");
      out.print( icon );
      out.write("</span>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.print( login.getUname() );
      out.write("</div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_modify\">내 정보 수정</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_book\">북마크 보기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_write\" onclick=\"book();\">글쓰기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_logout\">로그아웃</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

				}
			
      out.write('\r');
      out.write('\n');
      out.write(" \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/user_info.css\">   \r\n");
      out.write("<script>\r\n");
      out.write("var IsDuplicate = false;\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		/* 닉네임 포커스 로직 */\r\n");
      out.write("		$(\"#unick\").focus();\r\n");
      out.write("		\r\n");
      out.write("		/* 닉네임 & 비번 엔터시 저장로직 */\r\n");
      out.write("		$(\"#unick,#upw\").keyup(function(event){\r\n");
      out.write("			if(event.keyCode == 13)\r\n");
      out.write("			{\r\n");
      out.write("				change();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		//아이콘 클릭시 변경 가능한 아이콘 리스트 보여주고 다시 클릭시 안보이게 함\r\n");
      out.write("		$(\"#iconchange\")\r\n");
      out.write("		.click(function()\r\n");
      out.write("		{\r\n");
      out.write("			if($(\"#icon_show\").is(\":visible\"))\r\n");
      out.write("			{\r\n");
      out.write("				$(\"#icon_show\").css(\"display\",\"none\");\r\n");
      out.write("			}else\r\n");
      out.write("			{\r\n");
      out.write("				$(\"#icon_show\").toggle();\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("		//변경하려는 닉네임 중복여부 검증\r\n");
      out.write("		$(\"#unick\").keyup(function(){\r\n");
      out.write("			IsDuplicate = false;\r\n");
      out.write("			usernick = $(this).val();\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"nickcheck.jsp?unick=\" + usernick,\r\n");
      out.write("				type : \"get\",\r\n");
      out.write("				dataType : \"html\",\r\n");
      out.write("				success : function(result)\r\n");
      out.write("				{\r\n");
      out.write("					result = result.trim();\r\n");
      out.write("					switch(result)\r\n");
      out.write("					{\r\n");
      out.write("					case \"00\" : \r\n");
      out.write("						$(\"#btnmsg\").html(\"닉네임 체크 오류입니다.\");\r\n");
      out.write("						$(\"#btnmsg\").css(\"color\",\"blue\");\r\n");
      out.write("						break;\r\n");
      out.write("					case \"01\" : \r\n");
      out.write("						$(\"#btnmsg\").html(\"중복된 닉네임입니다.\");\r\n");
      out.write("						$(\"#btnmsg\").css(\"color\",\"red\");\r\n");
      out.write("						IsDuplicate = true;\r\n");
      out.write("						break;\r\n");
      out.write("					case \"02\" : \r\n");
      out.write("						$(\"#btnmsg\").html(\"사용 가능한 닉네임입니다.\");\r\n");
      out.write("						$(\"#btnmsg\").css(\"color\",\"green\");\r\n");
      out.write("						break;\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("		\r\n");
      out.write("	//회원정보변경로직 \r\n");
      out.write("	function change()\r\n");
      out.write("	{\r\n");
      out.write("		console.log($(\"input[name='uicon']:checked\").val());\r\n");
      out.write("		if($(\"#upw\").val() == \"\")\r\n");
      out.write("		{\r\n");
      out.write("			$(\"#upw\").focus();\r\n");
      out.write("			alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(confirm(\"저장하시겠습니까?\") == false)\r\n");
      out.write("		{\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($(\"#unick\").val() == \"");
      out.print( login.getUnick() );
      out.write("\")\r\n");
      out.write("		{\r\n");
      out.write("			$(\"#unick\").focus();\r\n");
      out.write("			alert(\"닉네임 변경사항이 없습니다.\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(IsDuplicate == true)\r\n");
      out.write("		{\r\n");
      out.write("			alert(\"중복된 닉네임입니다. 새로운 닉네임 입력하세요.\");\r\n");
      out.write("			$(\"#unick\").focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			url : \"user_infocheck.jsp\",\r\n");
      out.write("			data : \r\n");
      out.write("			{\r\n");
      out.write("				upw : $(\"#upw\").val(),\r\n");
      out.write("				unick : $(\"#unick\").val(),\r\n");
      out.write("				season : $(\"#season\").val(),\r\n");
      out.write("				local : $(\"#local\").val(),\r\n");
      out.write("				human : $(\"#human\").val(),\r\n");
      out.write("				move : $(\"#move\").val(),\r\n");
      out.write("				schedule : $(\"#schedule\").val(),\r\n");
      out.write("				uinout : $(\"#uinout\").val(),\r\n");
      out.write("				uicon : $(\"input[name='uicon']:checked\").val()\r\n");
      out.write("			},\r\n");
      out.write("			dataType : \"html\",\r\n");
      out.write("			success : function(result)\r\n");
      out.write("			{\r\n");
      out.write("				result = result.trim();\r\n");
      out.write("				switch(result)\r\n");
      out.write("				{\r\n");
      out.write("				case \"ERROR\" :\r\n");
      out.write("					alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("					$(\"#upw\").focus();\r\n");
      out.write("					break;\r\n");
      out.write("				case \"OK\" :\r\n");
      out.write("					alert(\"변경되었습니다.\");\r\n");
      out.write("					document.location = \"user_info.jsp\";\r\n");
      out.write("					break;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 취소로직 */\r\n");
      out.write("	function cancel()\r\n");
      out.write("	{\r\n");
      out.write("		window.location = \"../firstmain/lobby.jsp\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 회원탈퇴로직 */\r\n");
      out.write("	function gotoRetire()\r\n");
      out.write("	{\r\n");
      out.write("		window.location = \"../user/retire.jsp\";			\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	<form method=\"post\" name=\"user_info\" id=\"user_info\" action=\"user_infook.jsp\">\r\n");
      out.write("		<table border=\"0\" width=\"80%\" align=\"center\" >\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td style=\"width: 20%; vertical-align: top;\">\r\n");
      out.write("					<table border=\"0\" align=\"center\" width=\"80%\" height=\"550px\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td align=\"center\">\r\n");
      out.write("							<br><br><br>\r\n");
      out.write("							");

							String icon = "";
							switch (login.getUicon())
							{
		                		case "1": icon  = "😄"; break;     				  
		                		case "2": icon  = "😆"; break;  
		                		case "3": icon  = "😅"; break;  
		                		case "4": icon  = "😀"; break;  
		                		case "5": icon  = "😨"; break;  
		                		case "6": icon  = "👿"; break;  
		                		case "7": icon  = "😝"; break;  
		                		case "8": icon  = "😷"; break;  
		                		case "9": icon  = "😴"; break;  
		                		case "10": icon  = "😱"; break;  
			                }
							
      out.write("\r\n");
      out.write("							<div style=\"font-size:140px; margin:0px;\">");
      out.print( icon );
      out.write("</div><br>\r\n");
      out.write("							<h1>");
      out.print( login.getUnick() );
      out.write("</h1>\r\n");
      out.write("							<a style=\"font-size:20px;\"> 아이디 : ");
      out.print( login.getUid() );
      out.write(" </a><br>\r\n");
      out.write("							<a style=\"font-size:20px;\"> 이메일 : ");
      out.print( login.getEmail() );
      out.write("</a><br>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td align=\"center\">\r\n");
      out.write("								<button id=\"retire\" type=\"button\" onclick=\"gotoRetire();\" style=\"border-radius:0.5em; border:0px; width:120px; height:30px; font-size:20px;\">\r\n");
      out.write("								<b>회원탈퇴</b>\r\n");
      out.write("								</button>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"vertical_line\"></div>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<table border=\"0\" width=\"80%\" align=\"center\">\r\n");
      out.write("						<tr style=\"word-break:break-all; height:100px;\">\r\n");
      out.write("							<td colspan=\"4\">\r\n");
      out.write("							<section id=\"icon_show\">\r\n");
      out.write("								<input type=\"radio\" name=\"uicon\" value=\"1\" ");
      out.print( login.getUicon().equals("1") ? "checked" : "" );
      out.write(" style=\"width:20px;height:20px;\"><span style=\"font-size:40px\">😄</span>\r\n");
      out.write("								<input type=\"radio\" name=\"uicon\" value=\"2\" ");
      out.print( login.getUicon().equals("2") ? "checked" : "" );
      out.write(" style=\"width:20px;height:20px;\"><span style=\"font-size:40px\">😆</span>\r\n");
      out.write("								<input type=\"radio\" name=\"uicon\" value=\"3\" ");
      out.print( login.getUicon().equals("3") ? "checked" : "" );
      out.write(" style=\"width:20px;height:20px;\"><span style=\"font-size:40px\">😅</span>\r\n");
      out.write("								<input type=\"radio\" name=\"uicon\" value=\"4\" ");
      out.print( login.getUicon().equals("4") ? "checked" : "" );
      out.write(" style=\"width:20px;height:20px;\"><span style=\"font-size:40px\">😀</span>\r\n");
      out.write("								<input type=\"radio\" name=\"uicon\" value=\"5\" ");
      out.print( login.getUicon().equals("5") ? "checked" : "" );
      out.write(" style=\"width:20px;height:20px;\"><span style=\"font-size:40px\">😨</span>\r\n");
      out.write("								<input type=\"radio\" name=\"uicon\" value=\"6\" ");
      out.print( login.getUicon().equals("6") ? "checked" : "" );
      out.write(" style=\"width:20px;height:20px;\"><span style=\"font-size:40px\">👿</span>\r\n");
      out.write("								<input type=\"radio\" name=\"uicon\" value=\"7\" ");
      out.print( login.getUicon().equals("7") ? "checked" : "" );
      out.write(" style=\"width:20px;height:20px;\"><span style=\"font-size:40px\">😝</span>\r\n");
      out.write("								<input type=\"radio\" name=\"uicon\" value=\"8\" ");
      out.print( login.getUicon().equals("8") ? "checked" : "" );
      out.write(" style=\"width:20px;height:20px;\"><span style=\"font-size:40px\">😷</span>\r\n");
      out.write("								<input type=\"radio\" name=\"uicon\" value=\"9\" ");
      out.print( login.getUicon().equals("9") ? "checked" : "" );
      out.write(" style=\"width:20px;height:20px;\"><span style=\"font-size:40px\">😴</span>\r\n");
      out.write("								<input type=\"radio\" name=\"uicon\" value=\"10\" ");
      out.print( login.getUicon().equals("10") ? "checked" : "" );
      out.write(" style=\"width:20px;height:20px;\"><span style=\"font-size:40px\">😱</span>\r\n");
      out.write("							</section>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr style=\"height:100px;\">\r\n");
      out.write("							<td id=\"iconbtn\" style=\"font-size:90px; width:80px; padding-bottom:15px; vertical-align:bottom;\">\r\n");
      out.write("							");
      out.print( icon );
      out.write("\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<p style=\"font-weight:bold; font-size:25px;\">");
      out.print( login.getUnick() );
      out.write("</p>\r\n");
      out.write("								<a style=\"font-size:22px;\">");
      out.print( login.getEmail() );
      out.write("</a>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"2\">\r\n");
      out.write("								<button type=\"button\" id=\"iconchange\" style=\"border-radius:0.5em; border:0px; width:120px; height:30px; font-size:20px; font-weight:bold; cursor:pointer; cursor:hand;\">아이콘변경</button>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("					<hr style=\"margin-left:8%; margin-right:8%; border:2px solid lightgray;\">\r\n");
      out.write("					<table border=\"0\" height=\"5px\" align=\"center\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>&nbsp;</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("					<table border=\"0\" width=\"80%\" align=\"center\" >\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td align=\"left\" style=\"font-size:20px;\">\r\n");
      out.write("								&nbsp;&nbsp;&nbsp;&nbsp;<b>&nbsp;닉네임 &nbsp;:</b> \r\n");
      out.write("								<input type=\"text\" name=\"unick\" id=\"unick\" placeholder=\"변경하실 닉네임을 입력하세요\">\r\n");
      out.write("								<span id=\"btnmsg\" style=\"margin-top:0px; width: 70pt; height: 25pt; font-size:18px; font-weight:bold; margin-left:5px\"></span>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>	\r\n");
      out.write("							<td align=\"left\" style=\"font-size:20px;\">\r\n");
      out.write("								&nbsp;&nbsp;<b>비밀번호 :</b> \r\n");
      out.write("								<input type=\"password\" name=\"upw\" id=\"upw\" style=\"height:40px;\" placeholder=\"비밀번호를 입력하셔야 변경됩니다\">\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("					<table border=\"0\" height=\"5px\" align=\"center\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>&nbsp;</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("					<table border=\"0\" align=\"center\" width=\"80%\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"3\" style=\"text-align:left;\"><h2>관심분야</h2></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<select name=\"season\" id=\"season\" style=\"width: 200px;\">\r\n");
      out.write("									<option value=\"\" ");
      out.print( login.getSeason().equals("") ? "selected" : "" );
      out.write(" >계절</option>\r\n");
      out.write("									<option value=\"봄\" ");
      out.print( login.getSeason().equals("봄") ? "selected" : "" );
      out.write(">봄</option>\r\n");
      out.write("									<option value=\"여름\" ");
      out.print( login.getSeason().equals("여름") ? "selected" : "" );
      out.write(">여름</option>\r\n");
      out.write("									<option value=\"가을\" ");
      out.print( login.getSeason().equals("가을") ? "selected" : "" );
      out.write(">가을</option>\r\n");
      out.write("									<option value=\"겨울\" ");
      out.print( login.getSeason().equals("겨울") ? "selected" : "" );
      out.write(">겨울</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<select name=\"local\" id=\"local\" style=\"width: 200px;\">\r\n");
      out.write("									<option value=\"\" ");
      out.print( login.getLocal().equals("") ? "selected" : "" );
      out.write(">지역</option>\r\n");
      out.write("									<option value=\"서울경기도\" ");
      out.print( login.getLocal().equals("서울경기도") ? "selected" : "" );
      out.write(">서울,경기도</option>\r\n");
      out.write("									<option value=\"강원도\" ");
      out.print( login.getLocal().equals("강원도") ? "selected" : "" );
      out.write(">강원도</option>\r\n");
      out.write("									<option value=\"충청도\" ");
      out.print( login.getLocal().equals("충청도") ? "selected" : "" );
      out.write(">충청도</option>\r\n");
      out.write("									<option value=\"전북\" ");
      out.print( login.getLocal().equals("전북") ? "selected" : "" );
      out.write(">전라북도</option>\r\n");
      out.write("									<option value=\"전남\" ");
      out.print( login.getLocal().equals("전남") ? "selected" : "" );
      out.write(">전라남도</option>\r\n");
      out.write("									<option value=\"경북\" ");
      out.print( login.getLocal().equals("경북") ? "selected" : "" );
      out.write(">경상북도</option>\r\n");
      out.write("									<option value=\"경남\" ");
      out.print( login.getLocal().equals("경남") ? "selected" : "" );
      out.write(">경상남도</option>\r\n");
      out.write("									<option value=\"제주\" ");
      out.print( login.getLocal().equals("제주") ? "selected" : "" );
      out.write(">제주도</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<select name=\"human\" id=\"human\" style=\"width: 200px;\">\r\n");
      out.write("									<option value=\"\" ");
      out.print( login.getHuman().equals("") ? "selected" : "" );
      out.write(">동행</option>\r\n");
      out.write("									<option value=\"가족\" ");
      out.print( login.getHuman().equals("가족") ? "selected" : "" );
      out.write(">가족</option>\r\n");
      out.write("									<option value=\"연인\" ");
      out.print( login.getHuman().equals("연인") ? "selected" : "" );
      out.write(">연인</option>\r\n");
      out.write("									<option value=\"친구\" ");
      out.print( login.getHuman().equals("친구") ? "selected" : "" );
      out.write(">친구</option>\r\n");
      out.write("									<option value=\"반려견\" ");
      out.print( login.getHuman().equals("반려견") ? "selected" : "" );
      out.write(">반려견</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<select name=\"move\" id=\"move\" style=\"width: 200px;\">\r\n");
      out.write("									<option value=\"\" ");
      out.print( login.getMove().equals("") ? "selected" : "" );
      out.write(">이동</option>\r\n");
      out.write("									<option value=\"버스\" ");
      out.print( login.getMove().equals("버스") ? "selected" : "" );
      out.write(">버스</option>\r\n");
      out.write("									<option value=\"기차\" ");
      out.print( login.getMove().equals("기차") ? "selected" : "" );
      out.write(">기차</option>\r\n");
      out.write("									<option value=\"자가용\" ");
      out.print( login.getMove().equals("자가용") ? "selected" : "" );
      out.write(">자가용</option>\r\n");
      out.write("									<option value=\"자전거\" ");
      out.print( login.getMove().equals("자전거") ? "selected" : "" );
      out.write(">자전거</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<select name=\"schedule\" id=\"schedule\" style=\"width: 200px;\">\r\n");
      out.write("									<option value=\"\" ");
      out.print( login.getSchedule().equals("") ? "selected" : "" );
      out.write(">일정</option>\r\n");
      out.write("									<option value=\"당일\" ");
      out.print( login.getSchedule().equals("당일") ? "selected" : "" );
      out.write(">당일</option>\r\n");
      out.write("									<option value=\"숙박\" ");
      out.print( login.getSchedule().equals("숙박") ? "selected" : "" );
      out.write(">숙박</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<select name=\"uinout\" id=\"uinout\" style=\"width: 200px;\">\r\n");
      out.write("									<option value=\"\" ");
      out.print( login.getUinout().equals("") ? "selected" : "" );
      out.write(">장소</option>\r\n");
      out.write("									<option value=\"실내\" ");
      out.print( login.getUinout().equals("실내") ? "selected" : "" );
      out.write(">실내</option>\r\n");
      out.write("									<option value=\"실외\" ");
      out.print( login.getUinout().equals("실외") ? "selected" : "" );
      out.write(">실외</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"3\" style=\"text-align: right;\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"3\" style=\"text-align: right;\">\r\n");
      out.write("								<button type=\"button\" class=\"modify\"  style=\"background-color: orangered;\" onclick=\"cancel();\">취소</button>&nbsp;&nbsp;\r\n");
      out.write("								<button type=\"button\" class=\"modify\" id=\"save\" style=\"background-color: dodgerblue;\" onclick=\"change();\">저장</button>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
