/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-14 02:39:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.firstmain;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import trip.vo.*;
import trip.dao.*;
import trip.dto.*;
import java.io.*;
import java.util.*;
import trip.util.*;
import trip.vo.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/firstmain/../include/head.jsp", Long.valueOf(1718259960266L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(9);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("trip.vo");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("trip.dao");
    _jspx_imports_packages.add("trip.dto");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("trip.util");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  \r\n");

// 첨부파일 저장경로
String uploadPath = "D:\\BTEAM\\trip\\src\\main\\webapp\\upload";

//로그인 여부를 세션을 통해 검사한다
userVO login  = (userVO)session.getAttribute("login");

      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"utf-8\">\r\n");
      out.write("		<title>여행추천가이드</title>\r\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/lobby.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"../css/trip.css\"/>\r\n");
      out.write("	<script src=\"../js/jquery-3.7.1.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		window.onload = function()\r\n");
      out.write("		{\r\n");
      out.write("			$(\".header1\").click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../firstmain/lobby.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\".login\")\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				if($(\"#log_info\").is(\":visible\"))\r\n");
      out.write("				{\r\n");
      out.write("					$(\"#log_info\").css(\"display\",\"none\");\r\n");
      out.write("				}else\r\n");
      out.write("				{\r\n");
      out.write("					$(\"#log_info\").toggle();\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_info\").mouseleave(function()\r\n");
      out.write("			{	\r\n");
      out.write("				$(this).toggle();\r\n");
      out.write("			})	\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_login\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/login.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_join\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/join.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_modify\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			})\r\n");
      out.write("			.click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../master/user_info.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_write\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../board/write.jsp\";\r\n");
      out.write("			});		\r\n");
      out.write("			\r\n");
      out.write("			$(\"#log_admin\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../master/masterGonggiwrite.jsp\";\r\n");
      out.write("			});	\r\n");
      out.write("				\r\n");
      out.write("			$(\"#log_logout\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/logout.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#log_book\")\r\n");
      out.write("			.mouseover(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"lightgray\");\r\n");
      out.write("			})\r\n");
      out.write("			.mouseout(function()\r\n");
      out.write("			{\r\n");
      out.write("				$(this).css(\"background-color\", \"\");\r\n");
      out.write("			}).click(function()\r\n");
      out.write("			{\r\n");
      out.write("				document.location = \"../user/bookmark.jsp\";\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<style>\r\n");
      out.write("		.header1\r\n");
      out.write("		{\r\n");
      out.write("			cursor:pointer; cursor:hand;\r\n");
      out.write("		}	\r\n");
      out.write("	\r\n");
      out.write("		#log_info\r\n");
      out.write("		{\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			background-color: white;\r\n");
      out.write("			display: none;\r\n");
      out.write("			top: 67px;\r\n");
      out.write("			left: 1610px;\r\n");
      out.write("			z-index: 1;\r\n");
      out.write("			overflow: hidden;\r\n");
      out.write("			border-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_table\r\n");
      out.write("		{	\r\n");
      out.write("			border-top: none;\r\n");
      out.write("			border-bottom: none;\r\n");
      out.write("			background-color: ghostwhite;\r\n");
      out.write("  			border-style: hidden;\r\n");
      out.write("			border-radius : 10px;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.log_td\r\n");
      out.write("		{	\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			width: 200px;\r\n");
      out.write("			height: 50px;\r\n");
      out.write("			cursor:pointer; cursor:hand;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_logout\r\n");
      out.write("		{\r\n");
      out.write("			border-bottom-left-radius : 10px;\r\n");
      out.write("			border-bottom-right-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#log_login\r\n");
      out.write("		{\r\n");
      out.write("			border-top-left-radius : 10px;\r\n");
      out.write("			border-top-right-radius : 10px;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		");

			if(login == null)
			{
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ 로그인</div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_login\">로그인</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_join\">회원가입</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

			}else if(login.getAdmin().equals("Y"))
			{ 
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ \r\n");
      out.write("						\r\n");
      out.write("							");

							String icon = "😄";
							switch (login.getUicon())
							{
							case "1": icon  = "😄"; break;     				  
	                		case "2": icon  = "😆"; break;  
	                		case "3": icon  = "😅"; break;  
	                		case "4": icon  = "😀"; break;  
	                		case "5": icon  = "😨"; break;  
	                		case "6": icon  = "👿"; break;  
	                		case "7": icon  = "😝"; break;  
	                		case "8": icon  = "😷"; break;  
	                		case "9": icon  = "😴"; break;  
	                		case "10": icon  = "😱"; break;   
			                }
							
      out.write("\r\n");
      out.write("							<span style=\"font-size:30px\">");
      out.print( icon );
      out.write("</span>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						");
      out.print( login.getUname() );
      out.write(" </div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_modify\">내 정보 수정</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_book\">북마크 보기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_admin\">관리자 페이지</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_logout\">로그아웃</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

				}else
				{
				
      out.write("\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td><div class=\"header1\"></div></td>\r\n");
      out.write("						<td><div class=\"login\">≡ \r\n");
      out.write("						");

						String icon = "😄";
						switch (login.getUicon())
							{
	                		case "1": icon  = "😄"; break;     				  
	                		case "2": icon  = "😆"; break;  
	                		case "3": icon  = "😅"; break;  
	                		case "4": icon  = "😀"; break;  
	                		case "5": icon  = "😨"; break;  
	                		case "6": icon  = "👿"; break;  
	                		case "7": icon  = "😝"; break;  
	                		case "8": icon  = "😷"; break;  
	                		case "9": icon  = "😴"; break;  
	                		case "10": icon  = "😱"; break;  
			                }
							
      out.write("\r\n");
      out.write("							<span style=\"font-size:30px\">");
      out.print( icon );
      out.write("</span>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.print( login.getUname() );
      out.write("</div></td>\r\n");
      out.write("						</tr>	\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"hline\"></div>\r\n");
      out.write("					<div id=\"log_info\">\r\n");
      out.write("						<table border=\"1\" id=\"log_table\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_modify\">내 정보 수정</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_book\">북마크 보기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_write\" onclick=\"book();\">글쓰기</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"log_td\" id=\"log_logout\">로그아웃</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

				}
			
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/index2.css\">\r\n");
      out.write("<script src=\"../js/main.js\"></script>\r\n");

request.setCharacterEncoding("UTF-8");
String pageno  = request.getParameter("page");
String type  = request.getParameter("type");
String[] season   = request.getParameterValues("season"  );
String[] local    = request.getParameterValues("local"   );
String[] human    = request.getParameterValues("human"   );
String[] move     = request.getParameterValues("move"    );
String[] schedule = request.getParameterValues("schedule");
String[] uinout   = request.getParameterValues("uinout"  );
String[] keyword   = request.getParameterValues("keyword"  );
if(pageno  == null) pageno  = "1";
if(type    == null) type    = "T";
if(keyword == null) keyword = new String[] {""};

//슬라이드 게시물 조회
adminboardDTO dto = new adminboardDTO();
ArrayList<adminboardVO> alist = dto.GetList(1);
System.out.println("가져온 데이터 갯수 : "+alist.size());

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function()\r\n");
      out.write("{\r\n");
      out.write("	var firstSlide = \r\n");
      out.write("	$('.slider').find('li').first()			// 첫번째 슬라이드		\r\n");
      out.write("	.stop(true).animate({'opacity':1},200);	// 첫번째 슬라이드만 보이게 하기\r\n");
      out.write("      \r\n");
      out.write("	// 이전버튼 함수\r\n");
      out.write("	function PrevSlide()\r\n");
      out.write("	{ \r\n");
      out.write("	    stopSlide(); startSlide();		//타이머 초기화\r\n");
      out.write("	    \r\n");
      out.write("	    var lastSlide = $('.slider').find('li').last()	//마지막 슬라이드\r\n");
      out.write("	    .prependTo( $('.slider'));						//마지막 슬라이드를 맨 앞으로 보내기	\r\n");
      out.write("	     						  \r\n");
      out.write("	    secondSlide =  $('.slider').find('li').eq(1)	//두 번째 슬라이드 구하기\r\n");
      out.write("	    .stop(true).animate({'opacity':0},400); 		//밀려난 두 번째 슬라이드는 fadeOut 시키고\r\n");
      out.write("	    \r\n");
      out.write("	    firstSlide =  $('.slider').find('li').first() 	//맨 처음 슬라이드 다시 구하기\r\n");
      out.write("	    .stop(true).animate({'opacity':1},400);			//새로 들어온 첫 번째 슬라이드는 fadeIn 시키기\r\n");
      out.write("	 }\r\n");
      out.write("	 \r\n");
      out.write("	// 다음 버튼 함수	  \r\n");
      out.write("  	function NextSlide()\r\n");
      out.write("  	{ \r\n");
      out.write("   	 	stopSlide();startSlide();		//타이머 초기화\r\n");
      out.write("   	 	\r\n");
      out.write("    	firstSlide = $('.slider').find('li').first() 	// 첫 번째 슬라이드\r\n");
      out.write("	    .appendTo($('.slider')); 					 	// 맨 마지막으로 보내기\r\n");
      out.write("	    \r\n");
      out.write("	    var lastSlide = $('.slider').find('li').last() 	// 맨 마지막으로 보낸 슬라이드\r\n");
      out.write("	    .stop(true).animate({'opacity':0},400); 		// fadeOut시키기\r\n");
      out.write("	    \r\n");
      out.write("	    firstSlide = $('.slider').find('li').first()	// 맨 처음 슬라이드\r\n");
      out.write("	    .stop(true).animate({'opacity':1},400);			// fadeIn 시키기\r\n");
      out.write(" 	 }\r\n");
      out.write("  \r\n");
      out.write("    $('#next').on('click', function()\r\n");
      out.write("	{ \r\n");
      out.write("		// 다음버튼 클릭\r\n");
      out.write("    	NextSlide();\r\n");
      out.write("    });\r\n");
      out.write("  \r\n");
      out.write("	 $('#prev').on('click', function()\r\n");
      out.write("	 { \r\n");
      out.write("		// 이전 버튼 클릭\r\n");
      out.write("	 	PrevSlide();\r\n");
      out.write("	 });\r\n");
      out.write("  \r\n");
      out.write("	// 자동 슬라이드 시작\r\n");
      out.write("	startSlide();\r\n");
      out.write("	var theInterval;\r\n");
      out.write("	\r\n");
      out.write("	//자동 슬라이드 설정\r\n");
      out.write("	function startSlide()\r\n");
      out.write("	{\r\n");
      out.write("		theInterval = setInterval(NextSlide, 5000); \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//자동 멈추기\r\n");
      out.write("	function stopSlide() \r\n");
      out.write("	{ \r\n");
      out.write("		clearInterval(theInterval);\r\n");
      out.write("	}\r\n");
      out.write("	  \r\n");
      out.write("	//마우스 오버시 슬라이드 멈춤\r\n");
      out.write("	$('.slider').hover(function()\r\n");
      out.write("	{ \r\n");
      out.write("		stopSlide();\r\n");
      out.write("	}, \r\n");
      out.write("	function()\r\n");
      out.write("	{\r\n");
      out.write("		startSlide();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("	//이전페이지에서 받아온 season\r\n");
      out.write("	");

	String   season_list = "";
	if(season != null)
	{
		for(String item : season)
		{
			if(!season_list.equals(""))
			{
				season_list += ",";
			}
			season_list += item;
		}
	}
	
      out.write("\r\n");
      out.write("	var season_list = \"");
      out.print( season_list );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function()\r\n");
      out.write("	{\r\n");
      out.write("		let vimg = '';		\r\n");
      out.write("		console.log(season_list);\r\n");
      out.write("\r\n");
      out.write("		var flag = false;\r\n");
      out.write("	\r\n");
      out.write("		season_ary = season_list.split(\",\");\r\n");
      out.write("\r\n");
      out.write("		for(i = 0 ; i < season_ary.length; i++)\r\n");
      out.write("		{\r\n");
      out.write("			season = season_ary[i];		\r\n");
      out.write("			\r\n");
      out.write("			if($(\".sub_list\").find(\"#rm\" + season).length > 0)\r\n");
      out.write("			{\r\n");
      out.write("				continue;\r\n");
      out.write("			}\r\n");
      out.write("			switch(season)\r\n");
      out.write("			{	//계절\r\n");
      out.write("				case '봄' :\r\n");
      out.write("					vimg = $('<img>', {\r\n");
      out.write("					 	'src' : '../image/spring.jpg',\r\n");
      out.write("					  	'width' : '130px',\r\n");
      out.write("					   	'height' : '100px'\r\n");
      out.write("					   	});\r\n");
      out.write("	\r\n");
      out.write("					var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('봄');\" id=\"rm봄\">`);\r\n");
      out.write("	\r\n");
      out.write("					$(newItem).append(vimg);\r\n");
      out.write("					$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + season + '</div>');\r\n");
      out.write("					$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"season\" value=\"' + season + '\">');\r\n");
      out.write("	\r\n");
      out.write("					$(\".sub_list\").append(newItem);\r\n");
      out.write("					break;\r\n");
      out.write("	\r\n");
      out.write("				case '여름' :\r\n");
      out.write("					vimg = $('<img>', {\r\n");
      out.write("					 	'src' : '../image/summer.jpg',\r\n");
      out.write("					  	'width' : '130px',\r\n");
      out.write("					   	'height' : '100px'\r\n");
      out.write("					   	});\r\n");
      out.write("	\r\n");
      out.write("					var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('여름');\" id=\"rm여름\">`);\r\n");
      out.write("	\r\n");
      out.write("					$(newItem).append(vimg);\r\n");
      out.write("					$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + season + '</div>');\r\n");
      out.write("					$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"season\" value=\"' + season + '\">');\r\n");
      out.write("					$(\".sub_list\").append(newItem);\r\n");
      out.write("					break;\r\n");
      out.write("	\r\n");
      out.write("				case '가을' :\r\n");
      out.write("					vimg = $('<img>', {\r\n");
      out.write("					 	'src' : '../image/autumn.jpg',\r\n");
      out.write("					  	'width' : '130px',\r\n");
      out.write("					   	'height' : '100px'\r\n");
      out.write("					   	});\r\n");
      out.write("	\r\n");
      out.write("					var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('가을');\" id=\"rm가을\">`);\r\n");
      out.write("	\r\n");
      out.write("					$(newItem).append(vimg);\r\n");
      out.write("					$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + season + '</div>');\r\n");
      out.write("					$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"season\" value=\"' + season + '\">');\r\n");
      out.write("					$(\".sub_list\").append(newItem);\r\n");
      out.write("					break;\r\n");
      out.write("	\r\n");
      out.write("				case '겨울' :\r\n");
      out.write("					vimg = $('<img>', {\r\n");
      out.write("					 	'src' : '../image/winter.jpg',\r\n");
      out.write("					  	'width' : '130px',\r\n");
      out.write("					   	'height' : '100px'\r\n");
      out.write("					   	});\r\n");
      out.write("	\r\n");
      out.write("					var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('겨울');\" id=\"rm겨울\">`);\r\n");
      out.write("	\r\n");
      out.write("					$(newItem).append(vimg);\r\n");
      out.write("					$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + season + '</div>');\r\n");
      out.write("					$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"season\" value=\"' + season + '\">');\r\n");
      out.write("					$(\".sub_list\").append(newItem);\r\n");
      out.write("					break;\r\n");
      out.write("			};\r\n");
      out.write("		};\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//이전페이지에서 받아온 local\r\n");
      out.write("	");

	String   local_list = "";
	if(local != null)
	{
		for(String item : local)
		{
			if(!local_list.equals(""))
			{
				local_list += ",";
			}
			local_list += item;
		}
	}
	
      out.write("\r\n");
      out.write("	var local_list = \"");
      out.print( local_list );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function()\r\n");
      out.write("	{\r\n");
      out.write("		let vimg = '';		\r\n");
      out.write("		console.log(local_list);\r\n");
      out.write("\r\n");
      out.write("		var flag = false;\r\n");
      out.write("	\r\n");
      out.write("		local_ary = local_list.split(\",\");\r\n");
      out.write("\r\n");
      out.write("		for(i = 0 ; i < local_ary.length; i++)\r\n");
      out.write("		{\r\n");
      out.write("			local = local_ary[i];		\r\n");
      out.write("			\r\n");
      out.write("			if($(\".sub_list\").find(\"#rm\" + local).length > 0)\r\n");
      out.write("			{\r\n");
      out.write("				continue;\r\n");
      out.write("			}\r\n");
      out.write("		switch(local)\r\n");
      out.write("		{	//계절\r\n");
      out.write("			case '서울경기도' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/경기.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('서울경기도');\" id=\"rm서울경기도\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + local + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"local\" value=\"' + local + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '강원도' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/강원.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('강원도');\" id=\"rm강원도\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + local + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"local\" value=\"' + local + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '충청도' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/충청도.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('충청도');\" id=\"rm충청도\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + local + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"local\" value=\"' + local + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '전북' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/전북.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('전북');\" id=\"rm전북\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + local + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"local\" value=\"' + local + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '전남' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/전남.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('전남');\" id=\"rm전남\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + local + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"local\" value=\"' + local + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '경북' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/경북.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('경북');\" id=\"rm경북\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + local + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"local\" value=\"' + local + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '경남' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/경남.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('경남');\" id=\"rm경남\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + local + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"local\" value=\"' + local + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '제주' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/제주.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('제주');\" id=\"rm제주\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + local + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"local\" value=\"' + local + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//이전페이지에서 받아온 human\r\n");
      out.write("	");

	String   human_list = "";
	if(human != null)
	{
		for(String item : human)
		{
			if(!human_list.equals(""))
			{
				human_list += ",";
			}
			human_list += item;
		}
	}
	
      out.write("\r\n");
      out.write("	var human_list = \"");
      out.print( human_list );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function()\r\n");
      out.write("	{\r\n");
      out.write("		let vimg = '';		\r\n");
      out.write("		console.log(human_list);\r\n");
      out.write("\r\n");
      out.write("		var flag = false;\r\n");
      out.write("	\r\n");
      out.write("		human_ary = human_list.split(\",\");\r\n");
      out.write("\r\n");
      out.write("		for(i = 0 ; i < human_ary.length; i++)\r\n");
      out.write("		{\r\n");
      out.write("			human = human_ary[i];		\r\n");
      out.write("			\r\n");
      out.write("			if($(\".sub_list\").find(\"#rm\" + human).length > 0)\r\n");
      out.write("			{\r\n");
      out.write("				continue;\r\n");
      out.write("			}\r\n");
      out.write("		switch(human)\r\n");
      out.write("		{	//가족\r\n");
      out.write("			case '가족' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/family.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('가족');\" id=\"rm가족\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + human + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"human\" value=\"' + human + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '연인' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/lover.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('연인');\" id=\"rm연인\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + human + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"human\" value=\"' + human + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '친구' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/friend.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('친구');\" id=\"rm친구\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + human + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"human\" value=\"' + human + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '반려견' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/dog.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('반려견');\" id=\"rm반려견\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + human + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"human\" value=\"' + human + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//이전페이지에서 받아온 move\r\n");
      out.write("	");

	String  move_list = "";
	if(move != null)
	{
		for(String item : move)
		{
			if(!move_list.equals(""))
			{
				move_list += ",";
			}
			move_list += item;
		}
	}
	
      out.write("\r\n");
      out.write("	var move_list = \"");
      out.print( move_list );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function()\r\n");
      out.write("	{\r\n");
      out.write("		let vimg = '';		\r\n");
      out.write("		console.log(move_list);\r\n");
      out.write("\r\n");
      out.write("		var flag = false;\r\n");
      out.write("	\r\n");
      out.write("		move_ary = move_list.split(\",\");\r\n");
      out.write("\r\n");
      out.write("		for(i = 0 ; i < move_ary.length; i++)\r\n");
      out.write("		{\r\n");
      out.write("			move = move_ary[i];		\r\n");
      out.write("			\r\n");
      out.write("			if($(\".sub_list\").find(\"#rm\" + move).length > 0)\r\n");
      out.write("			{\r\n");
      out.write("				continue;\r\n");
      out.write("			}\r\n");
      out.write("		switch(move)\r\n");
      out.write("		{	//이동수단\r\n");
      out.write("			case '버스' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/bus.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('버스');\" id=\"rm버스\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + move + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"move\" value=\"' + move + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '기차' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/train.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('기차');\" id=\"rm기차\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + move + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"move\" value=\"' + move + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '자가용' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/car.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('자가용');\" id=\"rm자가용\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + move + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"move\" value=\"' + move + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '자전거' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/cycle.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('자전거');\" id=\"rm자전거\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + move + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"move\" value=\"' + move + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//이전페이지에서 받아온 schedule\r\n");
      out.write("	");

	String  schedule_list = "";
	if(schedule != null)
	{
		for(String item : schedule)
		{
			if(!schedule_list.equals(""))
			{
				schedule_list += ",";
			}
			schedule_list += item;
		}
	}
	
      out.write("\r\n");
      out.write("	var schedule_list = \"");
      out.print(schedule_list );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function()\r\n");
      out.write("	{\r\n");
      out.write("		let vimg = '';		\r\n");
      out.write("		console.log(schedule_list);\r\n");
      out.write("\r\n");
      out.write("		var flag = false;\r\n");
      out.write("	\r\n");
      out.write("		schedule_ary = schedule_list.split(\",\");\r\n");
      out.write("\r\n");
      out.write("		for(i = 0 ; i < schedule_ary.length; i++)\r\n");
      out.write("		{\r\n");
      out.write("			schedule = schedule_ary[i];		\r\n");
      out.write("			\r\n");
      out.write("			if($(\".sub_list\").find(\"#rm\" + schedule).length > 0)\r\n");
      out.write("			{\r\n");
      out.write("				continue;\r\n");
      out.write("			}\r\n");
      out.write("		switch(schedule)\r\n");
      out.write("		{	//일정\r\n");
      out.write("			case '당일' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/당일치기.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('당일');\" id=\"rm당일\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + schedule + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"schedule\" value=\"' + schedule + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '숙박' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/숙박.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('숙박');\" id=\"rm숙박\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + schedule + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"schedule\" value=\"' + schedule + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//이전페이지에서 받아온 uinout\r\n");
      out.write("	");

	String  uinout_list = "";
	if(uinout != null)
	{
		for(String item : uinout)
		{
			if(!uinout_list.equals(""))
			{
				uinout_list += ",";
			}
			uinout_list += item;
		}
	}
	
      out.write("\r\n");
      out.write("	var uinout_list = \"");
      out.print(uinout_list );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function()\r\n");
      out.write("	{\r\n");
      out.write("		let vimg = '';		\r\n");
      out.write("		console.log(uinout_list);\r\n");
      out.write("\r\n");
      out.write("		var flag = false;\r\n");
      out.write("	\r\n");
      out.write("		uinout_ary = uinout_list.split(\",\");\r\n");
      out.write("\r\n");
      out.write("		for(i = 0 ; i < uinout_ary.length; i++)\r\n");
      out.write("		{\r\n");
      out.write("			uinout = uinout_ary[i];		\r\n");
      out.write("			\r\n");
      out.write("			if($(\".sub_list\").find(\"#rm\" + uinout).length > 0)\r\n");
      out.write("			{\r\n");
      out.write("				continue;\r\n");
      out.write("			}\r\n");
      out.write("		switch(uinout)\r\n");
      out.write("		{	//장소\r\n");
      out.write("			case '실내' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/inside.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('실내');\" id=\"rm실내\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + uinout + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"uinout\" value=\"' + uinout + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("			case '실외' :\r\n");
      out.write("				vimg = $('<img>', {\r\n");
      out.write("				 	'src' : '../image/outside.jpg',\r\n");
      out.write("				  	'width' : '130px',\r\n");
      out.write("				   	'height' : '100px'\r\n");
      out.write("				   	});\r\n");
      out.write("\r\n");
      out.write("				var newItem = $(`<div class=\"menu_itemsub\" onclick=\"removeCart('실외');\" id=\"rm실외\">`);\r\n");
      out.write("\r\n");
      out.write("				$(newItem).append(vimg);\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + uinout + '</div>');\r\n");
      out.write("				$(newItem).html($(newItem).html()+'<input type=\"hidden\" name=\"uinout\" value=\"' + uinout + '\">');\r\n");
      out.write("\r\n");
      out.write("				$(\".sub_list\").append(newItem);\r\n");
      out.write("				break;\r\n");
      out.write("				\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var login_season = \"\";	\r\n");
      out.write("	var login_local = \"\";	\r\n");
      out.write("	var login_human = \"\";	\r\n");
      out.write("	var login_move = \"\";	\r\n");
      out.write("	var login_schedule = \"\";	\r\n");
      out.write("	var login_uinout = \"\";	\r\n");
      out.write("		\r\n");
      out.write("	");

	if( login != null)
	{	
      out.write("\r\n");
      out.write("		login_season = '");
      out.print(login.getSeason() );
      out.write("';  // 회원가입시 추천 계절\r\n");
      out.write("		login_local = '");
      out.print(login.getLocal() );
      out.write("';  // 회원가입시 지역\r\n");
      out.write("		login_human = '");
      out.print(login.getHuman() );
      out.write("';  // 회원가입시 동행\r\n");
      out.write("		login_move = '");
      out.print(login.getMove() );
      out.write("';  // 회원가입시 이동\r\n");
      out.write("		login_schedule = '");
      out.print(login.getSchedule() );
      out.write("';  // 회원가입시 일정\r\n");
      out.write("		login_uinout = '");
      out.print(login.getUinout() );
      out.write("';  // 회원가입시 장소\r\n");
	} 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	$(document).ready(function()\r\n");
      out.write("	{\r\n");
      out.write("		let vimg = '';\r\n");
      out.write("		console.log(login_season);\r\n");
      out.write("\r\n");
      out.write("		var flag = false;\r\n");
      out.write("\r\n");
      out.write("		if($(\"#reco_show\").find(\"#rm\" + login_season).length > 0)\r\n");
      out.write("		{\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if($(\"#reco_show\").find(\"#rm\" + login_local).length > 0)\r\n");
      out.write("		{\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if($(\"#reco_show\").find(\"#rm\" + login_human).length > 0)\r\n");
      out.write("		{\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if($(\"#reco_show\").find(\"#rm\" + login_move).length > 0)\r\n");
      out.write("		{\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if($(\"#reco_show\").find(\"#rm\" + login_schedule).length > 0)\r\n");
      out.write("		{\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if($(\"#reco_show\").find(\"#rm\" + login_uinout).length > 0)\r\n");
      out.write("		{\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		switch(login_season)\r\n");
      out.write("		{	//계절\r\n");
      out.write("		\r\n");
      out.write("		case '봄' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/spring.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('봄');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_season + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '여름' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/summer.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('여름');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_season + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '가을' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/autumn.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('가을');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_season + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '겨울' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/winter.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('겨울');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_season + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		switch(login_local)\r\n");
      out.write("		{	//지역\r\n");
      out.write("		\r\n");
      out.write("		case '서울경기도' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/경기.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('서울경기도');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_local + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '강원도' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/강원.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('강원도');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_local + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '충청도' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/충청도.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('충청도');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_local + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '전북' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/전북.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('전북');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_local + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '전남' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/전남.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('전남');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_local + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '경북' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/경북.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('경북');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_local + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '경남' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/경남.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('경남');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_local + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '제주' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/제주.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('제주');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_local + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		switch(login_human)\r\n");
      out.write("		{	//동행\r\n");
      out.write("		\r\n");
      out.write("		case '가족' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/family.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('가족');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_human + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '연인' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/lover.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('연인');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_human + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '친구' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/friend.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('친구');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_human + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '반려견' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/dog.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('반려견');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_human + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		switch(login_move)\r\n");
      out.write("		{	//이동수단\r\n");
      out.write("		\r\n");
      out.write("		case '버스' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/bus.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('버스');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_move + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '기차' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/train.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('기차');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_move + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '자가용' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/car.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('자가용');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_move + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '자전거' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/cycle.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('자전거');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_move + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		switch(login_schedule)\r\n");
      out.write("		{	//일정\r\n");
      out.write("		\r\n");
      out.write("		case '당일' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/당일치기.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('당일');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_schedule + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '숙박' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/숙박.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('숙박');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_schedule + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		switch(login_uinout)\r\n");
      out.write("		{	//장소\r\n");
      out.write("		\r\n");
      out.write("		case '실내' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/inside.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('실내');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_uinout + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("			\r\n");
      out.write("		case '실외' :\r\n");
      out.write("			vimg = $('<img>', {\r\n");
      out.write("			 	'src' : '../image/outside.jpg',\r\n");
      out.write("			  	'width' : '200px',\r\n");
      out.write("			   	'height' : '130px'\r\n");
      out.write("			   	});\r\n");
      out.write("			\r\n");
      out.write("			var newItem = $(`<div class=\"menu_item\" onclick=\"addCart('실외');\">`);\r\n");
      out.write("\r\n");
      out.write("			$(newItem).append(vimg);\r\n");
      out.write("			$(newItem).html($(newItem).html()+'<div class=\"mdiv\">' + login_uinout + '</div>');\r\n");
      out.write("\r\n");
      out.write("			$(\"#reco_show\").append(newItem);\r\n");
      out.write("			break;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("	<table border=\"0\" width=\"100%\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"15%\" rowspan=\"5\" class=\"ibtn\" style=\"vertical-align:middle;\">\r\n");
      out.write("				<div>\r\n");
      out.write("				<div id=\"idiv1\" class=\"btnbox\" style=\"background-color:#1abc9b; color:white;\" onclick=\"tablechange('추천');\">추천</div>\r\n");
      out.write("				<div id=\"idiv2\" class=\"btnbox\" onclick=\"tablechange('계절');\">계절</div>\r\n");
      out.write("				<div id=\"idiv3\" class=\"btnbox\" onclick=\"tablechange('지역');\">지역</div>\r\n");
      out.write("				<div id=\"idiv4\" class=\"btnbox\" onclick=\"tablechange('동행');\">동행</div>\r\n");
      out.write("				<div id=\"idiv5\" class=\"btnbox\" onclick=\"tablechange('이동');\">이동</div>\r\n");
      out.write("				<div id=\"idiv6\" class=\"btnbox\" onclick=\"tablechange('일정');\">일정</div>\r\n");
      out.write("				<div id=\"idiv7\" class=\"btnbox\" onclick=\"tablechange('장소');\">장소</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td colspan=\"4\" align=\"center\" width=\"80%\" height=\"120px\">\r\n");
      out.write("				<table border=\"0\" width=\"1500px\" height=\"200px\">\r\n");
      out.write("					<tr border=\"0\">\r\n");
      out.write("						<td style=\"width:50px\"><div class=\"btn\"><button type=\"button\" id=\"prev\" style=\"width: 35px;\">◀️</button></div>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td style=\"text-align:center;\">\r\n");
      out.write("							<section style=\"height: 100px;\">\r\n");
      out.write("							<ul class=\"slider\">\r\n");
      out.write("							");
  
							for(adminboardVO vo : alist)
							{								
								
      out.write("\r\n");
      out.write("								<li id=\"divSlide\">\r\n");
      out.write("									<div style=\"background-image: url(../upload/");
      out.print( vo.getPname() );
      out.write(");  width: 1400px; height: 200px; \">  \r\n");
      out.write("										<dl class=\"right\">\r\n");
      out.write("											<dt></dt>\r\n");
      out.write("											<dd></dd>\r\n");
      out.write("										</dl>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>	\r\n");
      out.write("								");

							}
							
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("						</section>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td style=\"width:50px\"><div class=\"btn\"><button type=\"button\" id=\"next\" style=\"width: 35px;\">▶️</button></div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr height=\"300px\" style=\"vertical-align:top;\">\r\n");
      out.write("			<td width=\"150px\" align=\"center\" height=\"100%\" colspan=\"3\" >\r\n");
      out.write("				<section id=\"reco_show\">\r\n");
      out.write("					\r\n");
      out.write("				</section>\r\n");
      out.write("			<section id=\"season_show\">\r\n");
      out.write("				<div class=\"menu_item\" onclick=\"addCart('봄');\">\r\n");
      out.write("					<img src=\"../image/spring.jpg\" width=\"200px\" height=\"130px\"><br>\r\n");
      out.write("					<div class=\"mdiv\">봄</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"menu_item\" onclick=\"addCart('여름');\">\r\n");
      out.write("					<img src=\"../image/summer.jpg\" width=\"200px\" height=\"130px\"><br>\r\n");
      out.write("					<div class=\"mdiv\">여름</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"menu_item\" onclick=\"addCart('가을');\">\r\n");
      out.write("					<img src=\"../image/autumn.jpg\" width=\"200px\" height=\"130px\"><br>\r\n");
      out.write("					<div class=\"mdiv\">가을</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"menu_item\" onclick=\"addCart('겨울');\">\r\n");
      out.write("					<img src=\"../image/winter.jpg\" width=\"200px\" height=\"130px\"><br>\r\n");
      out.write("					<div class=\"mdiv\">겨울</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("			<section id=\"local_show\">\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('서울경기도');\">\r\n");
      out.write("						<img src=\"../image/경기.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">서울,경기도</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('강원도');\">\r\n");
      out.write("						<img src=\"../image/강원.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">강원도</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('충청도');\">\r\n");
      out.write("						<img src=\"../image/충청도.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">충청도</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('전북');\">\r\n");
      out.write("						<img src=\"../image/전북.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">전라북도</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('전남');\">\r\n");
      out.write("						<img src=\"../image/전남.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">전라남도</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('경북');\">\r\n");
      out.write("						<img src=\"../image/경북.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">경상북도</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('경남');\">\r\n");
      out.write("						<img src=\"../image/경남.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">경상남도</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('제주');\">\r\n");
      out.write("						<img src=\"../image/제주.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">제주도</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("				<section id=\"human_show\">\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('가족');\">\r\n");
      out.write("						<img src=\"../image/family.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">가족</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('연인');\">\r\n");
      out.write("						<img src=\"../image/lover.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">연인</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('친구');\">\r\n");
      out.write("						<img src=\"../image/friend.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">친구</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('반려견');\">\r\n");
      out.write("						<img src=\"../image/dog.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">반려견</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("				<section id=\"move_show\">\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('버스');\">\r\n");
      out.write("						<img src=\"../image/bus.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">버스</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('기차');\">\r\n");
      out.write("						<img src=\"../image/train.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">기차</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('자가용');\">\r\n");
      out.write("						<img src=\"../image/car.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">자가용</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('자전거');\">\r\n");
      out.write("						<img src=\"../image/cycle.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">자전거</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("				<section id=\"schedule_show\">\r\n");
      out.write("				<div class=\"menu_item\" onclick=\"addCart('당일');\">\r\n");
      out.write("					<img src=\"../image/당일치기.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("					<div class=\"mdiv\">당일</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"menu_item\" onclick=\"addCart('숙박');\">\r\n");
      out.write("					<img src=\"../image/숙박.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("					<div class=\"mdiv\">숙박</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				</section>\r\n");
      out.write("				<section id=\"inout_show\">\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('실내');\">\r\n");
      out.write("						<img src=\"../image/inside.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">실내</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu_item\" onclick=\"addCart('실외');\">\r\n");
      out.write("						<img src=\"../image/outside.jpg\" width=\"200px\" height=\"130px\">\r\n");
      out.write("						<div class=\"mdiv\">실외</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr height=\"130px\">\r\n");
      out.write("			<td colspan=\"4\">\r\n");
      out.write("			<form id=\"search\" name=\"search\" method=\"get\" action=\"../board/search.jsp\">\r\n");
      out.write("				<table class=\"line\" width=\"1500px\" height=\"170px\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>\r\n");
      out.write("							<!-- 클릭했을때 추가되는 부분 -->\r\n");
      out.write("							<section class=\"sub_list\">\r\n");
      out.write("							</section>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td align=\"right\" style=\"vertical-align:center;\">\r\n");
      out.write("							<input type=\"submit\" class=\"sbtn\" value=\"검색\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("							&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</form>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
